<?php
if(!defined('ABSPATH'))exit;
/** Controlled per-user advisory session memory. Stored locally in WordPress user meta; no external transmission. */
function legacyx_ai_memory_key(){return '_legacyx_ai_advisor_session_v1';}
function legacyx_ai_memory_get($user_id=0){$user_id=$user_id?:get_current_user_id();$rows=get_user_meta($user_id,legacyx_ai_memory_key(),true);return is_array($rows)?array_slice($rows,-12):array();}
function legacyx_ai_memory_save($question,$answer,$client_id=0){if(!current_user_can('legacyx_view_reports'))return;$rows=legacyx_ai_memory_get();$rows[]=array('time'=>current_time('mysql'),'question'=>sanitize_text_field($question),'answer'=>array_values(array_map('sanitize_text_field',(array)$answer)),'client_id'=>absint($client_id));update_user_meta(get_current_user_id(),legacyx_ai_memory_key(),array_slice($rows,-12));}
function legacyx_ai_memory_clear(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');check_admin_referer('legacyx_ai_memory_clear');delete_user_meta(get_current_user_id(),legacyx_ai_memory_key());wp_safe_redirect(add_query_arg(array('page'=>'legacyx-ai-advisor','memory_cleared'=>'1'),admin_url('admin.php')));exit;}add_action('admin_post_legacyx_ai_memory_clear','legacyx_ai_memory_clear');
function legacyx_ai_memory_capture(){if(!current_user_can('legacyx_view_reports')||$_SERVER['REQUEST_METHOD']!=='POST'||empty($_POST['legacyx_ai_question'])||empty($_POST['legacyx_ai_context_nonce']))return;if(!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['legacyx_ai_context_nonce'])),'legacyx_ai_context'))return;$q=sanitize_text_field(wp_unslash($_POST['legacyx_ai_question']));$cid=isset($_POST['legacyx_ai_client'])?absint($_POST['legacyx_ai_client']):0;$a=function_exists('legacyx_ai_context_answer')?legacyx_ai_context_answer($q,$cid):array();if($a)legacyx_ai_memory_save($q,$a,$cid);}add_action('admin_init','legacyx_ai_memory_capture',20);
function legacyx_ai_memory_render(){if(!current_user_can('legacyx_view_reports'))return;$rows=array_reverse(legacyx_ai_memory_get());$clear=wp_nonce_url(admin_url('admin-post.php?action=legacyx_ai_memory_clear'),'legacyx_ai_memory_clear');?>
<section class="lxa-memory"><div class="lxa-memory-head"><div><span>PRIVATE SESSION MEMORY</span><h2>Advisor Conversation History</h2><p>Your latest advisory exchanges are stored locally in your WordPress user profile so you can preserve working context between questions.</p></div><?php if($rows):?><a class="button" href="<?php echo esc_url($clear);?>">Clear My Session</a><?php endif;?></div><?php if(isset($_GET['memory_cleared'])):?><div class="notice notice-success inline"><p>Advisor session memory cleared.</p></div><?php endif;?><?php if(!$rows):?><div class="lxa-memory-empty">No saved advisory exchanges yet. Ask the Advisor a question to begin a private working session.</div><?php else:?><div class="lxa-memory-list"><?php foreach($rows as $i=>$row):$client=$row['client_id']?get_the_title($row['client_id']):'Firm-wide';?><article><div><b><?php echo esc_html(sprintf('%02d',$i+1));?></b><small><?php echo esc_html($client);?> · <?php echo esc_html(mysql2date('M j, Y g:i a',$row['time']));?></small></div><h3><?php echo esc_html($row['question']);?></h3><?php foreach(array_slice((array)$row['answer'],0,4) as $line):?><p><?php echo esc_html($line);?></p><?php endforeach;?></article><?php endforeach;?></div><?php endif;?><small class="lxa-memory-note">Session memory is per authorized WordPress user and is not shared with clients or sent to an external AI provider.</small></section><?php }
function legacyx_ai_memory_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-ai-advisor')return;ob_start();legacyx_ai_memory_render();$html=ob_get_clean();?><div id="lxa-memory-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-memory-source'),status=document.querySelector('.lxa-ai-status');if(s&&status){var w=document.createElement('div');w.innerHTML=s.innerHTML;status.insertAdjacentElement('beforebegin',w.firstElementChild);s.remove();}});</script><?php }add_action('admin_footer','legacyx_ai_memory_inject',20);
function legacyx_ai_memory_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-memory',false);wp_enqueue_style('legacyx-ai-memory');$css='.lxa-memory{background:#f7f4ed;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxa-memory-head{display:flex;justify-content:space-between;gap:20px;align-items:start}.lxa-memory-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-memory-head h2{font:29px Georgia,serif;margin:5px 0}.lxa-memory-head p{color:#706a62;max-width:760px}.lxa-memory-list{display:grid;gap:12px;margin-top:20px}.lxa-memory-list article{background:#fff;border:1px solid #ded8ce;padding:20px}.lxa-memory-list article>div{display:flex;gap:12px;align-items:center}.lxa-memory-list b{color:#f05a16;font:20px Georgia,serif}.lxa-memory-list small,.lxa-memory-note{color:#817a72}.lxa-memory-list h3{font:20px Georgia,serif;margin:12px 0}.lxa-memory-list p{margin:7px 0;color:#5f5952}.lxa-memory-empty{background:#fff;border:1px dashed #cfc7bb;padding:20px;margin-top:18px;color:#706a62}.lxa-memory-note{display:block;margin-top:15px}@media(max-width:650px){.lxa-memory-head{display:block}.lxa-memory-head .button{margin-top:10px}}';wp_add_inline_style('legacyx-ai-memory',$css);}add_action('admin_enqueue_scripts','legacyx_ai_memory_styles');
