<?php
if(!defined('ABSPATH'))exit;
/** Phase 19 foundation: an explainable advisory workspace built from Firm OS records. No external model is connected yet. */
function legacyx_ai_advisor_menu(){add_submenu_page('legacyx-firm-os','Legacy X AI Advisor','AI Advisor','legacyx_view_reports','legacyx-ai-advisor','legacyx_render_ai_advisor');}
add_action('admin_menu','legacyx_ai_advisor_menu',24);
function legacyx_ai_advisor_brief(){
 if(!function_exists('legacyx_intelligence_snapshot'))return array();$s=legacyx_intelligence_snapshot();list($band,$copy)=legacyx_intelligence_band($s['overall']);$recs=legacyx_intelligence_recommendations($s);$watch=function_exists('legacyx_client_intelligence_watchlist_data')?legacyx_client_intelligence_watchlist_data(3):array();
 return array('snapshot'=>$s,'band'=>$band,'band_copy'=>$copy,'recommendations'=>$recs,'watch'=>$watch);
}
function legacyx_ai_advisor_prompt_library(){return array(
 'executive'=>array('Executive Brief','Summarize the current operating posture and management priorities from recorded Firm OS data.'),
 'delivery'=>array('Delivery Review','Explain current workflow pressure and which delivery areas deserve management review.'),
 'relationships'=>array('Relationship Review','Surface client relationships that deserve review based on current recorded intelligence.'),
 'billing'=>array('Billing Review','Summarize recorded billing operations and outstanding-balance signals without making financial claims.'),
);}
function legacyx_ai_advisor_answer($mode,$d){$s=$d['snapshot'];$lines=array();if($mode==='executive'){$lines[]='Current operating posture: '.$d['band'].' ('.$s['overall'].'/100).';$lines[]=$d['band_copy'];foreach(array_slice($d['recommendations'],0,3) as $r)$lines[]=$r[0].': '.$r[1];}elseif($mode==='delivery'){$lines[]='Client Delivery signal: '.$s['delivery'].'/100.';$lines[]='Recorded workflow: '.$s['open_work'].' open and '.$s['completed_work'].' completed work items.';$lines[]=$s['delivery']<70?'Management review is warranted for aging, blocked, or waiting workflow.':'The recorded delivery signal is currently stable; continue monitoring aging work.';}elseif($mode==='relationships'){$lines[]='Relationship Growth signal: '.$s['growth'].'/100.';if(!$d['watch'])$lines[]='No client watchlist records are currently available.';else foreach($d['watch'] as $r)$lines[]=$r['name'].' — '.$r['priority'].' posture, '.$r['score'].'/100.';}else{$lines[]='Billing Operations signal: '.$s['revenue'].'/100.';$lines[]='Recorded outstanding balance: '.(function_exists('legacyx_money')?legacyx_money($s['outstanding']):number_format($s['outstanding'],2)).'.';$lines[]='This is an internal operational summary of recorded billing fields, not audited revenue, accounting advice, or a collection determination.';}return $lines;}
function legacyx_render_ai_advisor(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');$d=legacyx_ai_advisor_brief();$modes=legacyx_ai_advisor_prompt_library();$mode=isset($_GET['advisor_mode'])?sanitize_key(wp_unslash($_GET['advisor_mode'])):'executive';if(!isset($modes[$mode]))$mode='executive';$answer=legacyx_ai_advisor_answer($mode,$d);?>
<div class="wrap lxa-ai"><section class="lxa-ai-hero"><div><span>PHASE 19 · LEGACY X AI ADVISOR</span><h1>Executive Advisory Workspace</h1><p>A controlled advisory interface that turns current Legacy X Firm OS intelligence into explainable management briefs. External generative AI is not connected yet.</p></div><div><small>Current Posture</small><strong><?php echo esc_html($d['band']);?></strong><em><?php echo esc_html($d['snapshot']['overall']);?> / 100</em></div></section><div class="lxa-ai-grid"><aside><h2>Advisor Modes</h2><?php foreach($modes as $key=>$m):$url=add_query_arg(array('page'=>'legacyx-ai-advisor','advisor_mode'=>$key),admin_url('admin.php'));?><a class="<?php echo $mode===$key?'active':'';?>" href="<?php echo esc_url($url);?>"><strong><?php echo esc_html($m[0]);?></strong><small><?php echo esc_html($m[1]);?></small></a><?php endforeach;?><a href="<?php echo esc_url(admin_url('admin.php?page=legacyx-intelligence'));?>"><strong>Open Intelligence</strong><small>Inspect the underlying operating signals.</small></a></aside><main><span>ADVISOR RESPONSE · <?php echo esc_html(strtoupper($modes[$mode][0]));?></span><h2>Management Brief</h2><div class="lxa-ai-response"><?php foreach($answer as $i=>$line):?><article><b><?php echo esc_html(sprintf('%02d',$i+1));?></b><p><?php echo esc_html($line);?></p></article><?php endforeach;?></div><div class="lxa-ai-next"><strong>Human decision boundary</strong><p>Use this workspace to organize management attention. It does not approve credit or funding, provide legal or investment advice, make underwriting decisions, guarantee outcomes, or replace professional judgment.</p><a class="button button-primary" href="<?php echo esc_url(admin_url('edit.php?post_type=legacyx_intel_action'));?>">Open Action Center</a></div></main></div><section class="lxa-ai-status"><strong>AI connection status</strong><p><b>Foundation mode:</b> the interface currently uses deterministic, explainable Firm OS intelligence. No API key, external LLM, or client data transmission has been enabled. A model connection will only be added with explicit configuration and data-governance safeguards.</p></section></div><?php }
function legacyx_ai_advisor_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-advisor',false);wp_enqueue_style('legacyx-ai-advisor');$css='.lxa-ai{max-width:1400px;margin:24px 24px 60px 4px;color:#171512}.lxa-ai-hero{background:#11100f;color:#fff;padding:38px 42px;display:flex;justify-content:space-between;gap:30px;align-items:end}.lxa-ai-hero span,.lxa-ai main>span{font-size:11px;letter-spacing:.16em;font-weight:800;color:#f05a16}.lxa-ai-hero h1{font:42px Georgia,serif;margin:8px 0}.lxa-ai-hero p{max-width:800px;color:#c9c3ba}.lxa-ai-hero>div:last-child{text-align:right}.lxa-ai-hero small,.lxa-ai-hero em{display:block;color:#c9c3ba}.lxa-ai-hero strong{display:block;font:30px Georgia,serif}.lxa-ai-grid{display:grid;grid-template-columns:320px 1fr;gap:18px;margin-top:18px}.lxa-ai-grid aside,.lxa-ai-grid main,.lxa-ai-status{background:#fff;border:1px solid #ded8ce;padding:26px}.lxa-ai h2{font:29px Georgia,serif}.lxa-ai-grid aside>a{display:block;text-decoration:none;color:#171512;padding:16px;border-top:1px solid #e5dfd6}.lxa-ai-grid aside>a.active{background:#171512;color:#fff;border-left:4px solid #f05a16}.lxa-ai-grid aside small{display:block;color:#777067;margin-top:5px}.lxa-ai-grid aside>a.active small{color:#c9c3ba}.lxa-ai-response article{display:grid;grid-template-columns:45px 1fr;gap:15px;border-top:1px solid #e5dfd6;padding:18px 0}.lxa-ai-response b{font:21px Georgia,serif;color:#f05a16}.lxa-ai-response p{margin:0;font-size:15px;line-height:1.65}.lxa-ai-next{background:#f7f4ed;padding:20px;margin-top:18px}.lxa-ai-next p,.lxa-ai-status p{color:#6f6961;line-height:1.6}.lxa-ai-status{margin-top:18px}.lxa-ai-status strong{font:22px Georgia,serif}@media(max-width:850px){.lxa-ai-grid{grid-template-columns:1fr}.lxa-ai-hero{display:block}.lxa-ai-hero>div:last-child{text-align:left;margin-top:22px}}@media(max-width:600px){.lxa-ai-hero{padding:28px 22px}.lxa-ai-hero h1{font-size:34px}}';wp_add_inline_style('legacyx-ai-advisor',$css);}add_action('admin_enqueue_scripts','legacyx_ai_advisor_styles');
