<?php
if(!defined('ABSPATH'))exit;
/** Provider-neutral adapter registry and model routing policy. No provider is enabled here. */
function legacyx_ai_provider_registry(){return apply_filters('legacyx_ai_provider_registry',array());}
function legacyx_ai_model_routes(){return array('executive'=>'executive_reasoning','delivery'=>'operations_reasoning','relationships'=>'relationship_reasoning','applications'=>'operations_reasoning','billing'=>'operations_reasoning');}
function legacyx_ai_route_profile($intent){$routes=legacyx_ai_model_routes();$intent=sanitize_key($intent);return $routes[$intent]??'executive_reasoning';}
function legacyx_ai_provider_adapter_status(){
 $cfg=function_exists('legacyx_ai_gateway_config')?legacyx_ai_gateway_config():array('provider'=>'disabled','enabled'=>false);
 $registry=legacyx_ai_provider_registry();$provider=$cfg['provider']??'disabled';$adapter=isset($registry[$provider])&&is_callable($registry[$provider])?$registry[$provider]:null;
 return array('provider'=>$provider,'gateway_enabled'=>!empty($cfg['enabled']),'adapter_ready'=>(bool)$adapter,'profiles'=>array_values(array_unique(legacyx_ai_model_routes())));
}
function legacyx_ai_provider_execute($prompt,$context=array(),$intent='executive'){
 if(!current_user_can('legacyx_view_reports'))return new WP_Error('legacyx_ai_access','Access denied.');
 $cfg=legacyx_ai_gateway_config();if(empty($cfg['enabled']))return new WP_Error('legacyx_ai_disabled','External AI is disabled.');
 if(function_exists('legacyx_ai_external_consent_status')&&!legacyx_ai_external_consent_status())return new WP_Error('legacyx_ai_consent','External AI consent is not enabled for this authorized user.');
 $safe=legacyx_ai_gateway_payload($context);$valid=legacyx_ai_gateway_validate($context,$safe);if(is_wp_error($valid)){if(function_exists('legacyx_ai_provider_audit_log'))legacyx_ai_provider_audit_log('adapter','blocked_sensitive',array_keys($safe));return $valid;}
 $registry=legacyx_ai_provider_registry();$provider=$cfg['provider'];if(empty($registry[$provider])||!is_callable($registry[$provider])){if(function_exists('legacyx_ai_provider_audit_log'))legacyx_ai_provider_audit_log('adapter','provider_not_registered',array_keys($safe));return new WP_Error('legacyx_ai_provider_not_registered','No approved provider adapter is registered.');}
 $request=array('prompt'=>sanitize_textarea_field($prompt),'context'=>$safe,'profile'=>legacyx_ai_route_profile($intent));
 $result=call_user_func($registry[$provider],$request,$cfg);
 if(function_exists('legacyx_ai_provider_audit_log'))legacyx_ai_provider_audit_log('adapter',is_wp_error($result)?$result->get_error_code():'completed',array_keys($safe));return $result;
}
function legacyx_ai_provider_adapter_panel(){if(!current_user_can('legacyx_view_reports'))return;$s=legacyx_ai_provider_adapter_status();$routes=legacyx_ai_model_routes();?>
<section class="lxa-adapter"><div class="lxa-adapter-head"><span>PROVIDER ADAPTER & MODEL ROUTING</span><h2>Controlled Model Architecture</h2><p>Legacy X now has a provider-neutral adapter boundary. Model selection is routed by operational intent instead of being hard-coded into client-facing or management workflows.</p></div><div class="lxa-adapter-state"><article><small>GATEWAY</small><strong><?php echo $s['gateway_enabled']?'Ready':'Off';?></strong></article><article><small>PROVIDER ADAPTER</small><strong><?php echo $s['adapter_ready']?'Registered':'Not Registered';?></strong></article><article><small>ACTIVE PROVIDER</small><strong><?php echo esc_html($s['provider']==='disabled'?'None':ucfirst($s['provider']));?></strong></article></div><div class="lxa-route-table"><h3>Routing Policy</h3><table><thead><tr><th>Advisor Intent</th><th>Model Profile</th><th>Purpose</th></tr></thead><tbody><?php foreach($routes as $intent=>$profile):?><tr><td><?php echo esc_html(ucfirst($intent));?></td><td><code><?php echo esc_html($profile);?></code></td><td><?php echo esc_html($profile==='executive_reasoning'?'Executive synthesis and management prioritization':($profile==='relationship_reasoning'?'Relationship-level operational interpretation':'Recorded operational workflow interpretation'));?></td></tr><?php endforeach;?></tbody></table></div><div class="lxa-adapter-rule"><strong>No provider is automatically selected.</strong> A real adapter must be explicitly registered in server-controlled code/configuration after provider approval. The public repository contains no API key and no active external model endpoint.</div></section><?php }
function legacyx_ai_provider_adapter_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-ai-advisor')return;ob_start();legacyx_ai_provider_adapter_panel();$html=ob_get_clean();?><div id="lxa-adapter-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-adapter-source'),p=document.querySelector('.lxa-provider-audit');if(s&&p){var w=document.createElement('div');w.innerHTML=s.innerHTML;p.insertAdjacentElement('afterend',w.firstElementChild);s.remove();}});</script><?php }add_action('admin_footer','legacyx_ai_provider_adapter_inject',60);
function legacyx_ai_provider_adapter_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-provider-adapter',false);wp_enqueue_style('legacyx-ai-provider-adapter');$css='.lxa-adapter{background:#f7f4ed;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxa-adapter-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-adapter-head h2{font:29px Georgia,serif;margin:6px 0}.lxa-adapter-head p{color:#706a62;max-width:850px}.lxa-adapter-state{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.lxa-adapter-state article{background:#fff;border:1px solid #ded8ce;padding:16px}.lxa-adapter-state small{display:block;color:#817a72;font-weight:800;letter-spacing:.08em}.lxa-adapter-state strong{display:block;font:22px Georgia,serif;margin-top:7px}.lxa-route-table{overflow:auto}.lxa-route-table h3{font:21px Georgia,serif}.lxa-route-table table{width:100%;border-collapse:collapse;background:#fff}.lxa-route-table th,.lxa-route-table td{text-align:left;padding:11px;border-bottom:1px solid #e5dfd5}.lxa-route-table code{background:#eee8de;padding:4px 7px}.lxa-adapter-rule{margin-top:18px;border-left:4px solid #f05a16;background:#fff;padding:15px;color:#5f5952}@media(max-width:760px){.lxa-adapter-state{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-ai-provider-adapter',$css);}add_action('admin_enqueue_scripts','legacyx_ai_provider_adapter_styles');
