<?php
if(!defined('ABSPATH'))exit;
/** Consent + metadata audit for future external AI requests. No prompts, responses, secrets or client PII are stored. */
function legacyx_ai_provider_audit_key(){return 'legacyx_ai_provider_audit_v1';}
function legacyx_ai_provider_audit_rows(){ $r=get_option(legacyx_ai_provider_audit_key(),array());return is_array($r)?array_slice($r,0,100):array(); }
function legacyx_ai_provider_audit_log($type,$status,$fields=array()){$rows=legacyx_ai_provider_audit_rows();array_unshift($rows,array('time'=>current_time('mysql'),'user'=>get_current_user_id(),'type'=>sanitize_key($type),'status'=>sanitize_text_field($status),'fields'=>array_values(array_map('sanitize_key',(array)$fields))));update_option(legacyx_ai_provider_audit_key(),array_slice($rows,0,100),false);}
function legacyx_ai_external_consent_key(){return '_legacyx_ai_external_consent_v1';}
function legacyx_ai_external_consent_status(){return get_user_meta(get_current_user_id(),legacyx_ai_external_consent_key(),true)==='1';}
function legacyx_ai_external_consent_update(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');check_admin_referer('legacyx_ai_external_consent');$enabled=!empty($_POST['external_ai_consent']);update_user_meta(get_current_user_id(),legacyx_ai_external_consent_key(),$enabled?'1':'0');legacyx_ai_provider_audit_log('consent',$enabled?'enabled':'disabled');wp_safe_redirect(add_query_arg(array('page'=>'legacyx-ai-advisor','consent_saved'=>'1'),admin_url('admin.php')));exit;}add_action('admin_post_legacyx_ai_external_consent','legacyx_ai_external_consent_update');
function legacyx_ai_provider_audit_clear(){if(!current_user_can('legacyx_manage_automation'))wp_die('Access denied.');check_admin_referer('legacyx_ai_provider_audit_clear');delete_option(legacyx_ai_provider_audit_key());wp_safe_redirect(add_query_arg(array('page'=>'legacyx-ai-advisor','ai_audit_cleared'=>'1'),admin_url('admin.php')));exit;}add_action('admin_post_legacyx_ai_provider_audit_clear','legacyx_ai_provider_audit_clear');
function legacyx_ai_gateway_governed_request($prompt,$context=array()){
 if(!current_user_can('legacyx_view_reports'))return new WP_Error('legacyx_ai_access','Access denied.');
 if(!legacyx_ai_external_consent_status()){legacyx_ai_provider_audit_log('request','blocked_no_consent');return new WP_Error('legacyx_ai_consent','External AI request blocked: authorized-user consent is not enabled.');}
 $safe=function_exists('legacyx_ai_gateway_payload')?legacyx_ai_gateway_payload($context):array();$fields=array_keys($safe);$result=legacyx_ai_gateway_request($prompt,$context);
 legacyx_ai_provider_audit_log('request',is_wp_error($result)?$result->get_error_code():'completed',$fields);return $result;
}
function legacyx_ai_provider_audit_panel(){if(!current_user_can('legacyx_view_reports'))return;$consent=legacyx_ai_external_consent_status();$rows=legacyx_ai_provider_audit_rows();$clear=wp_nonce_url(admin_url('admin-post.php?action=legacyx_ai_provider_audit_clear'),'legacyx_ai_provider_audit_clear');?>
<section class="lxa-provider-audit"><div class="lxa-pa-head"><div><span>CONSENT & AUDIT</span><h2>External AI Control Record</h2><p>External AI requires both system-level gateway activation and explicit consent from the authorized management user initiating requests.</p></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="legacyx_ai_external_consent"><?php wp_nonce_field('legacyx_ai_external_consent');?><label><input type="checkbox" name="external_ai_consent" value="1" <?php checked($consent);?>> Allow my authorized requests to use the governed external AI gateway when a provider is activated.</label><button class="button" type="submit">Save Consent</button></form></div><?php if(isset($_GET['consent_saved'])):?><div class="notice notice-success inline"><p>External AI consent preference saved.</p></div><?php endif;?><div class="lxa-pa-state"><strong><?php echo $consent?'Consent Enabled':'Consent Disabled';?></strong><p>Consent alone does not activate an AI provider. The provider gateway remains independently controlled by server configuration.</p></div><div class="lxa-pa-table"><div class="lxa-pa-title"><h3>Governance Audit</h3><?php if($rows&&current_user_can('legacyx_manage_automation')):?><a class="button" onclick="return confirm('Clear the AI governance audit log?');" href="<?php echo esc_url($clear);?>">Clear Audit</a><?php endif;?></div><?php if(!$rows):?><p>No external AI governance events recorded yet.</p><?php else:?><table><thead><tr><th>Time</th><th>Actor</th><th>Event</th><th>Status</th><th>Approved Fields</th></tr></thead><tbody><?php foreach(array_slice($rows,0,20) as $r):$u=get_userdata(absint($r['user']));?><tr><td><?php echo esc_html(mysql2date('M j, Y g:i a',$r['time']));?></td><td><?php echo esc_html($u?$u->display_name:'User #'.absint($r['user']));?></td><td><?php echo esc_html(ucwords(str_replace('_',' ',$r['type'])));?></td><td><?php echo esc_html($r['status']);?></td><td><?php echo esc_html($r['fields']?implode(', ',$r['fields']):'—');?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div><small>Audit records contain metadata only. Raw prompts, model responses, API credentials and client-identifying fields are not written to this audit log.</small></section><?php }
function legacyx_ai_provider_audit_inject(){if(!current_user_can('legacyx_view_reports'))return;$s=get_current_screen();if(!$s||$s->id!=='firm-os_page_legacyx-ai-advisor')return;ob_start();legacyx_ai_provider_audit_panel();$html=ob_get_clean();?><div id="lxa-pa-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-pa-source'),g=document.querySelector('.lxa-gateway');if(s&&g){var w=document.createElement('div');w.innerHTML=s.innerHTML;g.insertAdjacentElement('afterend',w.firstElementChild);s.remove();}});</script><?php }add_action('admin_footer','legacyx_ai_provider_audit_inject',50);
function legacyx_ai_provider_audit_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-provider-audit',false);wp_enqueue_style('legacyx-ai-provider-audit');$css='.lxa-provider-audit{background:#fff;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxa-pa-head{display:grid;grid-template-columns:1.2fr 1fr;gap:24px}.lxa-pa-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-pa-head h2{font:29px Georgia,serif;margin:6px 0}.lxa-pa-head p,.lxa-provider-audit small{color:#706a62}.lxa-pa-head form{background:#f7f4ed;padding:18px}.lxa-pa-head label{display:block;line-height:1.5;margin-bottom:12px}.lxa-pa-state{border-left:4px solid #f05a16;background:#f7f4ed;padding:14px 18px;margin:20px 0}.lxa-pa-state strong{font:20px Georgia,serif}.lxa-pa-state p{margin:5px 0;color:#706a62}.lxa-pa-title{display:flex;justify-content:space-between;align-items:center}.lxa-pa-title h3{font:22px Georgia,serif}.lxa-pa-table{overflow:auto}.lxa-pa-table table{width:100%;border-collapse:collapse}.lxa-pa-table th,.lxa-pa-table td{text-align:left;border-bottom:1px solid #e7e1d8;padding:10px;font-size:12px}.lxa-provider-audit>small{display:block;margin-top:14px}@media(max-width:800px){.lxa-pa-head{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-ai-provider-audit',$css);}add_action('admin_enqueue_scripts','legacyx_ai_provider_audit_styles');
