<?php
if(!defined('ABSPATH'))exit;
/** OpenAI provider adapter. Disabled unless LEGACYX_AI_PROVIDER=openai and gateway constants are configured server-side. */
function legacyx_ai_openai_models(){return array('executive_reasoning'=>'gpt-5.6-sol','operations_reasoning'=>'gpt-5.6-terra','relationship_reasoning'=>'gpt-5.6-terra');}
function legacyx_ai_openai_register($registry){$registry['openai']='legacyx_ai_openai_request';return $registry;}add_filter('legacyx_ai_provider_registry','legacyx_ai_openai_register');
function legacyx_ai_openai_request($request,$cfg){
 if(empty($cfg['enabled'])||($cfg['provider']??'')!=='openai')return new WP_Error('legacyx_openai_disabled','OpenAI provider is not enabled.');
 if(!defined('LEGACYX_AI_API_KEY')||!LEGACYX_AI_API_KEY)return new WP_Error('legacyx_openai_key','OpenAI API key is not configured server-side.');
 $models=legacyx_ai_openai_models();$profile=sanitize_key($request['profile']??'executive_reasoning');$model=$models[$profile]??$models['executive_reasoning'];
 $endpoint=!empty($cfg['endpoint'])?$cfg['endpoint']:'https://api.openai.com/v1/responses';
 $system='You are the Legacy X Firm Executive AI Advisor. Use only the minimized operational context supplied. Provide concise management decision support. Never infer hidden personal data. Never approve credit or funding, make underwriting decisions, provide legal or investment advice, guarantee outcomes, or claim facts outside the supplied context. Distinguish recorded facts from recommendations. End with a short human-review next step.';
 $context=wp_json_encode((array)($request['context']??array()),JSON_UNESCAPED_SLASHES);
 $body=array('model'=>$model,'instructions'=>$system,'input'=>'Management question: '.sanitize_textarea_field($request['prompt']??'')."\n\nApproved operational context: ".$context,'max_output_tokens'=>900);
 $r=wp_remote_post($endpoint,array('timeout'=>45,'headers'=>array('Authorization'=>'Bearer '.LEGACYX_AI_API_KEY,'Content-Type'=>'application/json'),'body'=>wp_json_encode($body),'data_format'=>'body'));
 if(is_wp_error($r))return $r;$code=wp_remote_retrieve_response_code($r);$json=json_decode(wp_remote_retrieve_body($r),true);if($code<200||$code>=300)return new WP_Error('legacyx_openai_http','OpenAI request failed with HTTP '.$code.'.');
 $text='';if(!empty($json['output_text'])&&is_string($json['output_text']))$text=$json['output_text'];elseif(!empty($json['output'])&&is_array($json['output']))foreach($json['output'] as $item)if(!empty($item['content'])&&is_array($item['content']))foreach($item['content'] as $c)if(($c['type']??'')==='output_text'&&!empty($c['text']))$text.=$c['text'];
 if(!$text)return new WP_Error('legacyx_openai_empty','OpenAI returned no usable text output.');return array('provider'=>'openai','model'=>$model,'text'=>sanitize_textarea_field($text),'response_id'=>sanitize_text_field($json['id']??''));
}
function legacyx_ai_openai_panel(){if(!current_user_can('legacyx_view_reports'))return;$cfg=legacyx_ai_gateway_config();$active=($cfg['provider']??'')==='openai';?><section class="lxa-openai"><span>OPENAI ADAPTER</span><h2>Production Provider Readiness</h2><div class="lxa-openai-grid"><article><small>ADAPTER</small><strong>Installed</strong></article><article><small>PROVIDER SELECTED</small><strong><?php echo $active?'OpenAI':'Not Yet';?></strong></article><article><small>SERVER KEY</small><strong><?php echo !empty($cfg['key_ready'])?'Configured':'Required';?></strong></article></div><p>The adapter uses the OpenAI Responses API only after server-side activation. Executive reasoning routes to GPT-5.6 Sol; operational and relationship reasoning route to GPT-5.6 Terra. No API credential is stored in this theme or GitHub.</p><?php if(!$cfg['enabled']):?><div class="lxa-openai-stop"><strong>Configuration checkpoint:</strong> External requests remain blocked. The server still needs the OpenAI API key and gateway constants before production AI can be enabled.</div><?php endif;?></section><?php }
function legacyx_ai_openai_inject(){if(!current_user_can('legacyx_view_reports'))return;$s=get_current_screen();if(!$s||$s->id!=='firm-os_page_legacyx-ai-advisor')return;ob_start();legacyx_ai_openai_panel();$html=ob_get_clean();?><div id="lxa-openai-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-openai-source'),a=document.querySelector('.lxa-adapter');if(s&&a){var w=document.createElement('div');w.innerHTML=s.innerHTML;a.insertAdjacentElement('afterend',w.firstElementChild);s.remove();}});</script><?php }add_action('admin_footer','legacyx_ai_openai_inject',70);
function legacyx_ai_openai_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-openai',false);wp_enqueue_style('legacyx-ai-openai');$css='.lxa-openai{background:#fff;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxa-openai>span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-openai h2{font:29px Georgia,serif;margin:6px 0 18px}.lxa-openai-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.lxa-openai-grid article{background:#f7f4ed;padding:16px}.lxa-openai-grid small{display:block;color:#817a72;font-weight:800}.lxa-openai-grid strong{display:block;font:22px Georgia,serif;margin-top:6px}.lxa-openai>p{color:#706a62;max-width:900px}.lxa-openai-stop{border-left:4px solid #f05a16;background:#f7f4ed;padding:15px;margin-top:18px}@media(max-width:700px){.lxa-openai-grid{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-ai-openai',$css);}add_action('admin_enqueue_scripts','legacyx_ai_openai_styles');
