<?php
if(!defined('ABSPATH'))exit;
/**
 * Legacy X AI Provider Gateway.
 * Governance-first boundary for future external LLM connectivity.
 * No API credentials are stored here or in WordPress options.
 */
function legacyx_ai_gateway_config(){
 $provider=defined('LEGACYX_AI_PROVIDER')?sanitize_key(LEGACYX_AI_PROVIDER):'disabled';
 $endpoint=defined('LEGACYX_AI_ENDPOINT')?esc_url_raw(LEGACYX_AI_ENDPOINT):'';
 $key_ready=defined('LEGACYX_AI_API_KEY')&&LEGACYX_AI_API_KEY!=='';
 $enabled=defined('LEGACYX_AI_EXTERNAL_ENABLED')&&LEGACYX_AI_EXTERNAL_ENABLED===true;
 return array('provider'=>$provider,'endpoint'=>$endpoint,'key_ready'=>$key_ready,'enabled'=>$enabled&&$provider!=='disabled'&&$endpoint&&$key_ready);
}
function legacyx_ai_gateway_allowed_fields(){return array('operating_posture','operating_score','delivery_score','billing_score','growth_score','portfolio_score','open_work_count','completed_work_count','application_count','approved_count','relationship_posture','relationship_score','overdue_count','waiting_count','stalled_count');}
function legacyx_ai_gateway_payload($context){$safe=array();foreach(legacyx_ai_gateway_allowed_fields() as $k)if(isset($context[$k]))$safe[$k]=is_numeric($context[$k])?0+$context[$k]:sanitize_text_field($context[$k]);return $safe;}
function legacyx_ai_gateway_blocked_keys(){return array('name','email','phone','address','ssn','ein','tax_id','bank','account','routing','password','credential','document','document_url','full_name','business_name','client_id');}
function legacyx_ai_gateway_validate($raw,$safe){foreach(legacyx_ai_gateway_blocked_keys() as $key)if(array_key_exists($key,(array)$raw))return new WP_Error('legacyx_ai_sensitive_field','External AI request blocked: sensitive or identifying field detected.');if(!$safe)return new WP_Error('legacyx_ai_empty_context','External AI request blocked: no approved context fields.');return true;}
function legacyx_ai_gateway_request($prompt,$context=array()){
 if(!current_user_can('legacyx_view_reports'))return new WP_Error('legacyx_ai_access','Access denied.');
 $cfg=legacyx_ai_gateway_config();if(!$cfg['enabled'])return new WP_Error('legacyx_ai_disabled','External AI is disabled. Foundation Mode remains active.');
 $safe=legacyx_ai_gateway_payload($context);$valid=legacyx_ai_gateway_validate($context,$safe);if(is_wp_error($valid))return $valid;
 /* Provider adapter intentionally remains closed until a provider/model is explicitly approved and configured server-side. */
 return new WP_Error('legacyx_ai_adapter_pending','AI gateway governance is ready, but no provider adapter has been approved.');
}
function legacyx_ai_gateway_status(){return legacyx_ai_gateway_config();}
function legacyx_ai_gateway_admin_panel(){if(!current_user_can('legacyx_view_reports'))return;$c=legacyx_ai_gateway_status();$fields=legacyx_ai_gateway_allowed_fields();?>
<section class="lxa-gateway"><div class="lxa-gateway-head"><span>AI PROVIDER GATEWAY</span><h2>External AI Governance</h2><p>The gateway is designed to prevent uncontrolled Firm OS or Client 360 data from leaving WordPress. External AI remains off until a provider is explicitly approved and server-side credentials are configured.</p></div><div class="lxa-gateway-grid"><article><small>EXTERNAL CONNECTION</small><strong><?php echo $c['enabled']?'Enabled':'Disabled';?></strong><p><?php echo $c['enabled']?'Gateway prerequisites are configured. Provider adapter approval is still required.':'Legacy X Advisor continues in local Foundation Mode.';?></p></article><article><small>API KEY STORAGE</small><strong><?php echo $c['key_ready']?'Server Configured':'Not Configured';?></strong><p>Credentials are read only from server-side constants/environment configuration—not GitHub and not the WordPress database.</p></article><article><small>PROVIDER</small><strong><?php echo esc_html($c['provider']==='disabled'?'Not Selected':ucfirst($c['provider']));?></strong><p>No provider is contacted by this governance layer.</p></article></div><div class="lxa-gateway-policy"><h3>Approved outbound context</h3><p>Only minimized operational signals may pass the gateway:</p><div><?php foreach($fields as $f):?><code><?php echo esc_html($f);?></code><?php endforeach;?></div><h3>Always blocked</h3><p>Names, email addresses, phone numbers, addresses, SSNs, EIN/tax IDs, banking data, credentials, documents, document URLs, business names and internal client identifiers are not approved outbound fields.</p></div><div class="lxa-gateway-boundary"><strong>Human governance remains mandatory.</strong> External AI must never autonomously approve funding, determine creditworthiness, make legal determinations, execute investments, send money, or promise outcomes.</div></section><?php }
function legacyx_ai_gateway_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-ai-advisor')return;ob_start();legacyx_ai_gateway_admin_panel();$html=ob_get_clean();?><div id="lxa-gateway-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-gateway-source'),status=document.querySelector('.lxa-ai-status');if(s&&status){var w=document.createElement('div');w.innerHTML=s.innerHTML;status.insertAdjacentElement('beforebegin',w.firstElementChild);s.remove();}});</script><?php }add_action('admin_footer','legacyx_ai_gateway_inject',40);
function legacyx_ai_gateway_styles($hook){if($hook!=='firm-os_page_legacyx-ai-advisor')return;wp_register_style('legacyx-ai-gateway',false);wp_enqueue_style('legacyx-ai-gateway');$css='.lxa-gateway{background:#171512;color:#fff;padding:30px;margin-top:18px}.lxa-gateway-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-gateway-head h2{font:30px Georgia,serif;margin:6px 0}.lxa-gateway-head p{color:#c8c0b6;max-width:850px}.lxa-gateway-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:22px 0}.lxa-gateway-grid article{border:1px solid #39352f;padding:18px}.lxa-gateway-grid small{display:block;color:#a9a197;font-weight:800;letter-spacing:.1em}.lxa-gateway-grid strong{display:block;font:23px Georgia,serif;margin:8px 0;color:#fff}.lxa-gateway-grid p,.lxa-gateway-policy p{color:#c8c0b6}.lxa-gateway-policy{border-top:1px solid #39352f;padding-top:20px}.lxa-gateway-policy h3{font:20px Georgia,serif;margin-bottom:6px}.lxa-gateway-policy code{display:inline-block;background:#292622;color:#e8e1d7;padding:5px 8px;margin:3px;border-radius:2px}.lxa-gateway-boundary{background:#24211d;border-left:4px solid #f05a16;padding:16px;margin-top:20px;color:#d8d1c7}@media(max-width:800px){.lxa-gateway-grid{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-ai-gateway',$css);}add_action('admin_enqueue_scripts','legacyx_ai_gateway_styles');
