<?php
if(!defined('ABSPATH'))exit;
function legacyx_automation_audit_rows(){return array_slice((array)get_option('legacyx_automation_log_v1',array()),0,40);}
function legacyx_automation_audit_export(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');check_admin_referer('legacyx_automation_audit_export');$rows=legacyx_automation_audit_rows();nocache_headers();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="legacyx-automation-audit-'.current_time('Y-m-d').'.csv"');$out=fopen('php://output','w');fputcsv($out,array('Timestamp','Type','Activity'));foreach($rows as $r)fputcsv($out,array($r['time']??'',$r['type']??'info',$r['message']??''));fclose($out);exit;}
add_action('admin_post_legacyx_automation_audit_export','legacyx_automation_audit_export');
function legacyx_automation_audit_clear(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');check_admin_referer('legacyx_automation_audit_clear');update_option('legacyx_automation_log_v1',array(),false);wp_safe_redirect(admin_url('admin.php?page=legacyx-automation&audit_cleared=1'));exit;}
add_action('admin_post_legacyx_automation_audit_clear','legacyx_automation_audit_clear');
function legacyx_render_automation_audit(){if(!current_user_can('legacyx_view_reports'))return;$rows=legacyx_automation_audit_rows();$counts=array('success'=>0,'route'=>0,'escalation'=>0,'info'=>0);foreach($rows as $r){$t=$r['type']??'info';if(!isset($counts[$t]))$counts[$t]=0;$counts[$t]++;}?>
<section class="lxa-audit"><div class="lxa-audit-head"><div><span>AUTOMATION AUDIT & CONTROL</span><h2>Oversight Ledger</h2><p>Review what the engine recorded, when it occurred, and the operational reason represented by each logged event.</p></div><div class="lxa-audit-actions"><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="legacyx_automation_audit_export"><?php wp_nonce_field('legacyx_automation_audit_export');?><button class="button" type="submit">Export Audit CSV</button></form><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" onsubmit="return confirm('Clear the visible automation audit log? This cannot be undone.');"><input type="hidden" name="action" value="legacyx_automation_audit_clear"><?php wp_nonce_field('legacyx_automation_audit_clear');?><button class="button" type="submit">Clear Audit Log</button></form></div></div><div class="lxa-audit-metrics"><div><small>Logged Events</small><strong><?php echo esc_html(count($rows));?></strong></div><div><small>Scans</small><strong><?php echo esc_html($counts['success']);?></strong></div><div><small>Routing</small><strong><?php echo esc_html($counts['route']);?></strong></div><div><small>Escalations</small><strong><?php echo esc_html($counts['escalation']);?></strong></div></div><div class="lxa-audit-table"><div class="lxa-audit-row head"><span>Time</span><span>Type</span><span>Recorded Activity</span></div><?php if(!$rows):?><p>No automation audit events are currently recorded.</p><?php else:foreach($rows as $r):?><div class="lxa-audit-row"><span><?php echo esc_html($r['time']??'—');?></span><span><?php echo esc_html(ucfirst($r['type']??'info'));?></span><span><?php echo esc_html($r['message']??'');?></span></div><?php endforeach;endif;?></div><small class="lxa-audit-note">This ledger records the engine's internal operational log. It is not an immutable compliance archive and should not be treated as a substitute for regulated record-retention systems.</small></section><?php }
function legacyx_automation_audit_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-automation')return;ob_start();legacyx_render_automation_audit();$html=ob_get_clean();?><div id="lxa-audit-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-audit-source'),log=document.querySelector('.lxa-log');if(s&&log){var w=document.createElement('div');w.innerHTML=s.innerHTML;log.insertAdjacentElement('afterend',w.firstElementChild);s.remove();}});</script><?php }
add_action('admin_footer','legacyx_automation_audit_inject',11);
function legacyx_automation_audit_styles($hook){if($hook!=='firm-os_page_legacyx-automation')return;wp_register_style('legacyx-automation-audit',false);wp_enqueue_style('legacyx-automation-audit');$css='.lxa-audit{background:#fff;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxa-audit-head{display:flex;justify-content:space-between;gap:24px;align-items:end}.lxa-audit-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-audit-head h2{font:29px Georgia,serif;margin:5px 0 8px}.lxa-audit-head p{color:#746e65;margin:0;max-width:760px}.lxa-audit-actions{display:flex;gap:8px}.lxa-audit-actions form{margin:0}.lxa-audit-metrics{display:grid;grid-template-columns:repeat(4,1fr);background:#171512;color:#fff;margin-top:22px}.lxa-audit-metrics>div{padding:16px;border-right:1px solid #3b3732}.lxa-audit-metrics small{display:block;color:#aaa197}.lxa-audit-metrics strong{font:27px Georgia,serif}.lxa-audit-table{margin-top:20px}.lxa-audit-row{display:grid;grid-template-columns:1fr .6fr 3fr;gap:15px;padding:12px 10px;border-bottom:1px solid #ece7df}.lxa-audit-row.head{background:#f7f4ed;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.lxa-audit-note{display:block;color:#817a71;margin-top:14px}@media(max-width:800px){.lxa-audit-head{display:block}.lxa-audit-actions{margin-top:16px;flex-wrap:wrap}.lxa-audit-metrics{grid-template-columns:repeat(2,1fr)}.lxa-audit-row{grid-template-columns:1fr}.lxa-audit-row.head{display:none}}';wp_add_inline_style('legacyx-automation-audit',$css);}add_action('admin_enqueue_scripts','legacyx_automation_audit_styles');
