<?php
if(!defined('ABSPATH'))exit;

function legacyx_automation_route_map(){return array(
 'Automation · Overdue Workflow'=>array('cap'=>'legacyx_manage_workflow','label'=>'Workflow Team'),
 'Automation · Waiting on Client'=>array('cap'=>'legacyx_manage_workflow','label'=>'Workflow Team'),
 'Automation · Billing Review'=>array('cap'=>'legacyx_manage_billing','label'=>'Billing Manager'),
 'Automation · Application Aging'=>array('cap'=>'legacyx_manage_applications','label'=>'Applications Manager'),
);}
function legacyx_automation_find_owner($cap){$users=get_users(array('capability'=>$cap,'number'=>1,'orderby'=>'ID','order'=>'ASC'));if(!$users)return array(0,'Unassigned · '.$cap);$u=$users[0];return array((int)$u->ID,$u->display_name);}
function legacyx_automation_route_action($action_id){if(get_post_type($action_id)!=='legacyx_intel_action')return;$source=get_post_meta($action_id,'_legacyx_action_source',true);$map=legacyx_automation_route_map();if(!isset($map[$source]))return;$existing=(int)get_post_meta($action_id,'_legacyx_action_owner_user_id',true);if($existing)return;list($uid,$name)=legacyx_automation_find_owner($map[$source]['cap']);update_post_meta($action_id,'_legacyx_action_owner_user_id',$uid);update_post_meta($action_id,'_legacyx_action_owner',$name);update_post_meta($action_id,'_legacyx_action_route',$map[$source]['label']);if(function_exists('legacyx_automation_log'))legacyx_automation_log('Routed “'.get_the_title($action_id).'” to '.$name.'.','route');}
add_action('save_post_legacyx_intel_action','legacyx_automation_route_action',30);
function legacyx_automation_route_existing(){if(!post_type_exists('legacyx_intel_action'))return;$ids=get_posts(array('post_type'=>'legacyx_intel_action','post_status'=>'any','numberposts'=>100,'fields'=>'ids','meta_query'=>array(array('key'=>'_legacyx_automation_key','compare'=>'EXISTS'))));foreach($ids as $id)legacyx_automation_route_action($id);}
add_action('legacyx_automation_hourly','legacyx_automation_route_existing',20);
function legacyx_automation_reminder_summary(){if(!current_user_can('legacyx_access_firm_os'))return array();$today=current_time('Y-m-d');$args=array('post_type'=>'legacyx_intel_action','post_status'=>'any','numberposts'=>100,'meta_query'=>array(array('key'=>'_legacyx_action_status','value'=>array('Completed','Dismissed'),'compare'=>'NOT IN')));$actions=get_posts($args);$mine=array();$overdue=array();$due_soon=array();$uid=get_current_user_id();foreach($actions as $a){$owner=(int)get_post_meta($a->ID,'_legacyx_action_owner_user_id',true);$due=get_post_meta($a->ID,'_legacyx_action_due_date',true);if($owner===$uid)$mine[]=$a;if($due&&$due<$today)$overdue[]=$a;elseif($due&&$due<=date('Y-m-d',current_time('timestamp')+3*DAY_IN_SECONDS))$due_soon[]=$a;}return compact('mine','overdue','due_soon');}
function legacyx_automation_staff_notice(){if(!current_user_can('legacyx_access_firm_os'))return;$s=legacyx_automation_reminder_summary();if(!$s)return;$mine=count($s['mine']);$over=count($s['overdue']);$soon=count($s['due_soon']);if(!$mine&&!$over&&!$soon)return;$url=admin_url('edit.php?post_type=legacyx_intel_action');?><div class="notice notice-warning"><p><strong>Legacy X Automation:</strong> <?php echo esc_html($mine);?> assigned to you · <?php echo esc_html($over);?> overdue · <?php echo esc_html($soon);?> due within 3 days. <a href="<?php echo esc_url($url);?>">Open Action Center →</a></p></div><?php }
add_action('admin_notices','legacyx_automation_staff_notice');
function legacyx_automation_reminder_panel(){if(!current_user_can('legacyx_view_reports'))return;$s=legacyx_automation_reminder_summary();if(!$s)return;$url=admin_url('edit.php?post_type=legacyx_intel_action');?><section class="lxa-reminders"><div><span>AUTOMATION ROUTING</span><h2>Assignments & Reminders</h2><p>Automation-generated actions are routed to staff with the capability required for the originating module.</p></div><div class="lxa-reminder-metrics"><a href="<?php echo esc_url($url);?>"><small>My Assigned</small><strong><?php echo esc_html(count($s['mine']));?></strong></a><a href="<?php echo esc_url($url);?>"><small>Overdue</small><strong><?php echo esc_html(count($s['overdue']));?></strong></a><a href="<?php echo esc_url($url);?>"><small>Due Soon</small><strong><?php echo esc_html(count($s['due_soon']));?></strong></a></div></section><?php }
function legacyx_automation_reminder_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-automation')return;ob_start();legacyx_automation_reminder_panel();$html=ob_get_clean();if(!$html)return;?><div id="lxa-reminder-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-reminder-source'),hero=document.querySelector('.lxa-hero');if(s&&hero){var w=document.createElement('div');w.innerHTML=s.innerHTML;hero.insertAdjacentElement('afterend',w.firstElementChild);s.remove();}});</script><?php }
add_action('admin_footer','legacyx_automation_reminder_inject',8);
function legacyx_automation_routing_styles($hook){if($hook!=='firm-os_page_legacyx-automation')return;wp_register_style('legacyx-automation-routing',false);wp_enqueue_style('legacyx-automation-routing');$css='.lxa-reminders{display:grid;grid-template-columns:2fr 1fr;gap:24px;background:#f7f4ed;border:1px solid #ded8ce;padding:24px 28px;margin-top:18px}.lxa-reminders span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-reminders h2{font:27px Georgia,serif;margin:5px 0}.lxa-reminders p{color:#746e65;margin:0}.lxa-reminder-metrics{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #d8d1c6;background:#fff}.lxa-reminder-metrics a{padding:15px;text-decoration:none;color:#171512;border-right:1px solid #e4ded5}.lxa-reminder-metrics small{display:block;color:#746e65}.lxa-reminder-metrics strong{font:26px Georgia,serif}@media(max-width:800px){.lxa-reminders{grid-template-columns:1fr}.lxa-reminder-metrics{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-automation-routing',$css);}add_action('admin_enqueue_scripts','legacyx_automation_routing_styles');
