<?php
if(!defined('ABSPATH'))exit;

function legacyx_automation_escalation_scan(){
 if(!post_type_exists('legacyx_intel_action'))return 0;$today=current_time('Y-m-d');$changed=0;
 $actions=get_posts(array('post_type'=>'legacyx_intel_action','post_status'=>'any','numberposts'=>200,'meta_query'=>array(array('key'=>'_legacyx_action_status','value'=>array('Completed','Dismissed'),'compare'=>'NOT IN'))));
 foreach($actions as $a){$due=get_post_meta($a->ID,'_legacyx_action_due_date',true);if(!$due||$due>=$today)continue;$days=(int)floor((current_time('timestamp')-strtotime($due.' 00:00:00'))/DAY_IN_SECONDS);$current=get_post_meta($a->ID,'_legacyx_action_priority',true)?:'Normal';$target=$days>=7?'Critical':($days>=2?'High':$current);if($target===$current)continue;update_post_meta($a->ID,'_legacyx_action_priority',$target);update_post_meta($a->ID,'_legacyx_escalated_at',current_time('mysql'));update_post_meta($a->ID,'_legacyx_escalation_reason',$days.' day'.($days===1?'':'s').' overdue');$changed++;if(function_exists('legacyx_automation_log'))legacyx_automation_log('Escalated “'.get_the_title($a).'” to '.$target.' ('.$days.' days overdue).','escalation');}
 update_option('legacyx_automation_escalation_last_run',current_time('mysql'),false);return $changed;
}
add_action('legacyx_automation_hourly','legacyx_automation_escalation_scan',30);

function legacyx_automation_escalation_run_now(){if(!current_user_can('legacyx_view_reports'))wp_die('Access denied.');check_admin_referer('legacyx_escalation_run');$changed=legacyx_automation_escalation_scan();wp_safe_redirect(add_query_arg(array('page'=>'legacyx-automation','escalated'=>1,'changed'=>$changed),admin_url('admin.php')));exit;}
add_action('admin_post_legacyx_escalation_run','legacyx_automation_escalation_run_now');

function legacyx_automation_escalation_summary(){if(!current_user_can('legacyx_view_reports'))return array('critical'=>array(),'high'=>array());$rows=get_posts(array('post_type'=>'legacyx_intel_action','post_status'=>'any','numberposts'=>200,'meta_query'=>array(array('key'=>'_legacyx_action_status','value'=>array('Completed','Dismissed'),'compare'=>'NOT IN'))));$critical=$high=array();foreach($rows as $r){$p=get_post_meta($r->ID,'_legacyx_action_priority',true);if($p==='Critical')$critical[]=$r;elseif($p==='High')$high[]=$r;}return compact('critical','high');}
function legacyx_render_automation_escalation(){if(!current_user_can('legacyx_view_reports'))return;$s=legacyx_automation_escalation_summary();$last=get_option('legacyx_automation_escalation_last_run','Never');$url=admin_url('edit.php?post_type=legacyx_intel_action');?>
<section class="lxa-escalation"><div class="lxa-escalation-head"><div><span>EXECUTIVE ESCALATION</span><h2>Overdue Action Escalation</h2><p>Open management actions escalate to High after 2 overdue days and Critical after 7 overdue days. Escalation changes internal priority only.</p></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="legacyx_escalation_run"><?php wp_nonce_field('legacyx_escalation_run');?><button class="button button-primary" type="submit">Run Escalation Check</button></form></div><div class="lxa-escalation-metrics"><a href="<?php echo esc_url($url);?>"><small>Critical Open</small><strong><?php echo esc_html(count($s['critical']));?></strong><em>Review immediately →</em></a><a href="<?php echo esc_url($url);?>"><small>High Priority Open</small><strong><?php echo esc_html(count($s['high']));?></strong><em>Open Action Center →</em></a><div><small>Last Escalation Scan</small><strong class="date"><?php echo esc_html($last);?></strong><em>Hourly + manual control</em></div></div></section><?php }
function legacyx_automation_escalation_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='firm-os_page_legacyx-automation')return;ob_start();legacyx_render_automation_escalation();$html=ob_get_clean();?><div id="lxa-escalation-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var s=document.getElementById('lxa-escalation-source'),grid=document.querySelector('.lxa-grid');if(s&&grid){var w=document.createElement('div');w.innerHTML=s.innerHTML;grid.insertAdjacentElement('beforebegin',w.firstElementChild);s.remove();}});</script><?php }
add_action('admin_footer','legacyx_automation_escalation_inject',9);
function legacyx_automation_escalation_notice(){if(!current_user_can('legacyx_view_reports'))return;$s=legacyx_automation_escalation_summary();if(empty($s['critical']))return;$url=admin_url('edit.php?post_type=legacyx_intel_action');?><div class="notice notice-error"><p><strong>Legacy X Executive Escalation:</strong> <?php echo esc_html(count($s['critical']));?> critical management action<?php echo count($s['critical'])===1?'':'s';?> require review. <a href="<?php echo esc_url($url);?>">Review Action Center →</a></p></div><?php }
add_action('admin_notices','legacyx_automation_escalation_notice');
function legacyx_automation_escalation_styles($hook){if($hook!=='firm-os_page_legacyx-automation')return;wp_register_style('legacyx-automation-escalation',false);wp_enqueue_style('legacyx-automation-escalation');$css='.lxa-escalation{background:#171512;color:#fff;padding:28px;margin-top:18px}.lxa-escalation-head{display:flex;justify-content:space-between;align-items:end;gap:20px}.lxa-escalation-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxa-escalation-head h2{font:29px Georgia,serif;margin:5px 0 8px}.lxa-escalation-head p{color:#bcb5ab;margin:0;max-width:760px}.lxa-escalation-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#4b453e;margin-top:22px}.lxa-escalation-metrics>a,.lxa-escalation-metrics>div{background:#24211e;padding:20px;text-decoration:none;color:#fff}.lxa-escalation-metrics small,.lxa-escalation-metrics em{display:block;color:#aaa197;font-style:normal}.lxa-escalation-metrics strong{display:block;font:34px Georgia,serif;margin:5px 0}.lxa-escalation-metrics strong.date{font-size:16px;margin-top:12px}@media(max-width:800px){.lxa-escalation-head{display:block}.lxa-escalation-head form{margin-top:16px}.lxa-escalation-metrics{grid-template-columns:1fr}}';wp_add_inline_style('legacyx-automation-escalation',$css);}add_action('admin_enqueue_scripts','legacyx_automation_escalation_styles');
