<?php
if(!defined('ABSPATH'))exit;
function legacyx_register_billing_type(){register_post_type('legacyx_invoice',array('labels'=>array('name'=>'Billing & Payments','singular_name'=>'Invoice','add_new_item'=>'Add Invoice','edit_item'=>'Edit Invoice','menu_name'=>'Billing & Payments'),'public'=>false,'show_ui'=>true,'show_in_menu'=>true,'menu_icon'=>'dashicons-money-alt','supports'=>array('title'),'show_in_rest'=>false,'capability_type'=>'post','map_meta_cap'=>true));}add_action('init','legacyx_register_billing_type');
function legacyx_billing_meta_boxes(){add_meta_box('legacyx_billing_details','Invoice / Payment Details','legacyx_render_billing_box','legacyx_invoice','normal','high');}add_action('add_meta_boxes','legacyx_billing_meta_boxes');
function legacyx_render_billing_box($post){wp_nonce_field('legacyx_save_billing','legacyx_billing_nonce');$client_id=absint(get_post_meta($post->ID,'_legacyx_client_id',true));$status=get_post_meta($post->ID,'_legacyx_status',true);$type=get_post_meta($post->ID,'_legacyx_type',true);$clients=get_posts(array('post_type'=>'legacyx_client','post_status'=>'any','numberposts'=>-1,'orderby'=>'title','order'=>'ASC'));echo '<p><label><strong>Universal Client Profile</strong></label><br><select name="legacyx_client_id" style="width:100%"><option value="">Select client</option>';foreach($clients as $c){$cid=get_post_meta($c->ID,'_legacyx_client_id',true);echo '<option value="'.esc_attr($c->ID).'" '.selected($client_id,$c->ID,false).'>'.esc_html($c->post_title.' · '.$cid).'</option>';}echo '</select></p>';legacyx_billing_select('type','Record Type',$type,array('Invoice','Retainer','Service Fee','Installment','Credit / Adjustment'));legacyx_billing_select('status','Status',$status,array('Draft','Open','Partially Paid','Paid','Past Due','Waived','Refunded','Cancelled'));legacyx_billing_input($post,'invoice_number','Invoice Number');legacyx_billing_input($post,'amount_due','Amount Due');legacyx_billing_input($post,'amount_paid','Amount Paid');legacyx_billing_input($post,'issue_date','Issue Date','date');legacyx_billing_input($post,'due_date','Due Date','date');legacyx_billing_input($post,'paid_date','Paid Date','date');legacyx_billing_input($post,'payment_method','Payment Method / Reference');legacyx_billing_input($post,'payment_url','Authorized Payment URL','url');legacyx_billing_textarea($post,'description','Client-visible Description');legacyx_billing_textarea($post,'note','Billing Note / Next Action');echo '<p><small>Do not store card numbers, bank credentials, CVVs, SSNs, or payment-provider passwords here. Use an authorized external payment URL for payment collection.</small></p>';}
function legacyx_billing_input($post,$key,$label,$type='text'){$v=get_post_meta($post->ID,'_legacyx_'.$key,true);echo '<p><label><strong>'.esc_html($label).'</strong></label><br><input type="'.esc_attr($type).'" name="legacyx_'.esc_attr($key).'" value="'.esc_attr($v).'" style="width:100%"></p>';}
function legacyx_billing_textarea($post,$key,$label){$v=get_post_meta($post->ID,'_legacyx_'.$key,true);echo '<p><label><strong>'.esc_html($label).'</strong></label><br><textarea name="legacyx_'.esc_attr($key).'" style="width:100%;min-height:80px">'.esc_textarea($v).'</textarea></p>';}
function legacyx_billing_select($key,$label,$value,$options){echo '<p><label><strong>'.esc_html($label).'</strong></label><br><select name="legacyx_'.esc_attr($key).'" style="width:100%"><option value="">Select</option>';foreach($options as $o)echo '<option value="'.esc_attr($o).'" '.selected($value,$o,false).'>'.esc_html($o).'</option>';echo '</select></p>';}
function legacyx_save_billing($post_id){if(get_post_type($post_id)!=='legacyx_invoice')return;if(!isset($_POST['legacyx_billing_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['legacyx_billing_nonce'])),'legacyx_save_billing'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('edit_post',$post_id))return;$client=absint($_POST['legacyx_client_id']??0);update_post_meta($post_id,'_legacyx_client_id',$client);foreach(array('type','status','invoice_number','amount_due','amount_paid','issue_date','due_date','paid_date','payment_method') as $k)update_post_meta($post_id,'_legacyx_'.$k,sanitize_text_field(wp_unslash($_POST['legacyx_'.$k]??'')));foreach(array('description','note') as $k)update_post_meta($post_id,'_legacyx_'.$k,sanitize_textarea_field(wp_unslash($_POST['legacyx_'.$k]??'')));update_post_meta($post_id,'_legacyx_payment_url',esc_url_raw(wp_unslash($_POST['legacyx_payment_url']??'')));}add_action('save_post_legacyx_invoice','legacyx_save_billing');
function legacyx_get_client_billing($client_id){return get_posts(array('post_type'=>'legacyx_invoice','post_status'=>'any','numberposts'=>-1,'meta_key'=>'_legacyx_client_id','meta_value'=>absint($client_id),'orderby'=>'date','order'=>'DESC'));}
function legacyx_money($value){$n=preg_replace('/[^0-9.\-]/','',(string)$value);return $n!==''?'$'.number_format((float)$n,2):'$0.00';}
function legacyx_billing_effective_status($invoice_id){$status=get_post_meta($invoice_id,'_legacyx_status',true);if(in_array($status,array('Paid','Waived','Refunded','Cancelled','Draft'),true))return $status;$due=get_post_meta($invoice_id,'_legacyx_due_date',true);$amount=(float)preg_replace('/[^0-9.\-]/','',(string)get_post_meta($invoice_id,'_legacyx_amount_due',true));$paid=(float)preg_replace('/[^0-9.\-]/','',(string)get_post_meta($invoice_id,'_legacyx_amount_paid',true));if($amount>0&&$paid>=$amount)return 'Paid';if($paid>0&&$paid<$amount)$status='Partially Paid';if($due&&strtotime($due.' 23:59:59')<current_time('timestamp')&&$paid<$amount)return 'Past Due';if($status==='Past Due'&&$due&&strtotime($due.' 23:59:59')>=current_time('timestamp'))return $paid>0?'Partially Paid':'Open';return $status?:'Open';}
function legacyx_billing_counts($client_id){$rows=legacyx_get_client_billing($client_id);$out=array('total'=>count($rows),'open'=>0,'paid'=>0,'balance'=>0.0,'paid_amount'=>0.0);foreach($rows as $r){$s=legacyx_billing_effective_status($r->ID);$due=(float)preg_replace('/[^0-9.\-]/','',(string)get_post_meta($r->ID,'_legacyx_amount_due',true));$paid=(float)preg_replace('/[^0-9.\-]/','',(string)get_post_meta($r->ID,'_legacyx_amount_paid',true));if(in_array($s,array('Open','Partially Paid','Past Due'),true))$out['open']++;if($s==='Paid')$out['paid']++;$out['balance']+=max(0,$due-$paid);$out['paid_amount']+=$paid;}return $out;}
