<?php
if(!defined('ABSPATH'))exit;
function legacyx_client_intelligence_watchlist_data($limit=12){
 if(!current_user_can('legacyx_manage_clients')||!function_exists('legacyx_client_intelligence_snapshot'))return array();
 $clients=get_posts(array('post_type'=>'legacyx_client','post_status'=>'any','numberposts'=>100,'orderby'=>'modified','order'=>'DESC'));
 $rows=array();foreach($clients as $client){$s=legacyx_client_intelligence_snapshot($client->ID);if(!$s)continue;$rank=array('Priority'=>1,'Watch'=>2,'Stable'=>3,'Strong'=>4);$rows[]=array('id'=>$client->ID,'name'=>$client->post_title,'business'=>get_post_meta($client->ID,'_legacyx_business_name',true),'client_id'=>get_post_meta($client->ID,'_legacyx_client_id',true),'score'=>(int)$s['overall'],'priority'=>$s['priority'],'rank'=>$rank[$s['priority']]??5,'overdue'=>(int)$s['overdue'],'past_due'=>(int)$s['past_due'],'stalled'=>(int)$s['app_stalled'],'waiting'=>(int)$s['waiting']);}
 usort($rows,function($a,$b){if($a['rank']===$b['rank'])return $a['score']<=>$b['score'];return $a['rank']<=>$b['rank'];});return array_slice($rows,0,$limit);
}
function legacyx_client_intelligence_watchlist_summary($rows){$out=array('Priority'=>0,'Watch'=>0,'Stable'=>0,'Strong'=>0);foreach($rows as $r)if(isset($out[$r['priority']]))$out[$r['priority']]++;return $out;}
function legacyx_render_client_intelligence_watchlist(){if(!current_user_can('legacyx_manage_clients'))return;$rows=legacyx_client_intelligence_watchlist_data(12);$summary=legacyx_client_intelligence_watchlist_summary($rows);?>
<section class="lxi-watchlist"><div class="lxi-watch-head"><div><span>LEGACY X INTELLIGENCE</span><h2>Client Intelligence Watchlist</h2><p>Relationships ranked by recorded operational posture so management can focus attention where it is most needed.</p></div><a href="<?php echo esc_url(admin_url('admin.php?page=legacyx-intelligence'));?>">Open Intelligence →</a></div><div class="lxi-watch-summary"><?php foreach(array('Priority','Watch','Stable','Strong') as $label):?><div class="<?php echo esc_attr(strtolower($label));?>"><span><?php echo esc_html($label);?></span><strong><?php echo esc_html($summary[$label]);?></strong></div><?php endforeach;?></div><?php if(!$rows):?><p class="lxi-watch-empty">Client Intelligence will populate as Universal Client Profiles and operational records are created.</p><?php else:?><div class="lxi-watch-table"><div class="lxi-watch-row head"><span>Relationship</span><span>Posture</span><span>Score</span><span>Signals</span><span></span></div><?php foreach($rows as $r):$view=add_query_arg(array('page'=>'legacyx-client-360','client_id'=>$r['id']),admin_url('admin.php'));$signals=array();if($r['overdue'])$signals[]=$r['overdue'].' overdue';if($r['past_due'])$signals[]=$r['past_due'].' past due';if($r['stalled'])$signals[]=$r['stalled'].' stalled app';if($r['waiting'])$signals[]=$r['waiting'].' waiting';?><div class="lxi-watch-row"><span><strong><?php echo esc_html($r['name']);?></strong><small><?php echo esc_html(trim(($r['client_id']?:'').' · '.($r['business']?:'No business recorded'),' ·'));?></small></span><span><b class="lxi-posture <?php echo esc_attr(strtolower($r['priority']));?>"><?php echo esc_html($r['priority']);?></b></span><span><strong><?php echo esc_html($r['score']);?></strong></span><span><?php echo esc_html($signals?implode(' · ',$signals):'No exception signals');?></span><span><a href="<?php echo esc_url($view);?>">Open 360 →</a></span></div><?php endforeach;?></div><?php endif;?><small class="lxi-watch-boundary">Internal management aid based on Legacy X Firm OS records. Relationship scores are heuristic operating indicators, not financial, legal, credit, underwriting, or investment decisions.</small></section>
<?php }
function legacyx_client_intelligence_watchlist_inject(){if(!current_user_can('legacyx_manage_clients'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='toplevel_page_legacyx-firm-os')return;ob_start();legacyx_render_client_intelligence_watchlist();$html=ob_get_clean();if(!$html)return;?><div id="legacyx-watchlist-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var src=document.getElementById('legacyx-watchlist-source'),metrics=document.querySelector('.legacyx-staff-metrics');if(src&&metrics){var wrap=document.createElement('div');wrap.innerHTML=src.innerHTML;metrics.insertAdjacentElement('afterend',wrap.firstElementChild);src.remove();}});</script><?php }
add_action('admin_footer','legacyx_client_intelligence_watchlist_inject');
function legacyx_client_intelligence_watchlist_styles($hook){if($hook!=='toplevel_page_legacyx-firm-os')return;wp_register_style('legacyx-client-watchlist',false);wp_enqueue_style('legacyx-client-watchlist');$css='.lxi-watchlist{background:#fff;border:1px solid #ded8ce;padding:28px;margin-top:18px}.lxi-watch-head{display:flex;justify-content:space-between;gap:24px;align-items:end}.lxi-watch-head span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxi-watch-head h2{font:29px Georgia,serif;margin:5px 0 8px}.lxi-watch-head p{color:#746e65;margin:0;max-width:760px}.lxi-watch-head>a,.lxi-watch-row a{color:#171512;font-weight:800;text-decoration:none}.lxi-watch-summary{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #e4dfd6;margin-top:22px}.lxi-watch-summary>div{padding:16px 18px;border-right:1px solid #e4dfd6}.lxi-watch-summary span{display:block;color:#746e65}.lxi-watch-summary strong{display:block;font:27px Georgia,serif;margin-top:4px}.lxi-watch-table{margin-top:18px}.lxi-watch-row{display:grid;grid-template-columns:2fr .8fr .5fr 1.5fr .7fr;gap:12px;align-items:center;padding:14px 10px;border-bottom:1px solid #ece7df}.lxi-watch-row.head{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;background:#f7f4ed}.lxi-watch-row small{display:block;color:#746e65;margin-top:4px}.lxi-posture{display:inline-block;padding:5px 8px;font-size:11px}.lxi-posture.priority{background:#fde8e7;color:#8a1c13}.lxi-posture.watch{background:#fff0e8;color:#a4430e}.lxi-posture.stable{background:#f0eee9;color:#5f574e}.lxi-posture.strong{background:#eaf3ea;color:#315b32}.lxi-watch-boundary{display:block;color:#817a71;margin-top:16px}.lxi-watch-empty{color:#746e65}@media(max-width:1000px){.lxi-watch-row{grid-template-columns:1.5fr .7fr .4fr 1fr .6fr}}@media(max-width:700px){.lxi-watch-head{display:block}.lxi-watch-head>a{display:inline-block;margin-top:14px}.lxi-watch-summary{grid-template-columns:repeat(2,1fr)}.lxi-watch-row{grid-template-columns:1fr 1fr}.lxi-watch-row.head{display:none}.lxi-watch-row>span:nth-child(4),.lxi-watch-row>span:nth-child(5){grid-column:1/-1}}';wp_add_inline_style('legacyx-client-watchlist',$css);}add_action('admin_enqueue_scripts','legacyx_client_intelligence_watchlist_styles');
