<?php
if(!defined('ABSPATH'))exit;
function legacyx_register_client_role(){if(!get_role('legacyx_client'))add_role('legacyx_client','Legacy X Client',array('read'=>true));}add_action('init','legacyx_register_client_role',5);
function legacyx_client_login_redirect($redirect_to,$requested,$user){if($user instanceof WP_User&&in_array('legacyx_client',(array)$user->roles,true))return home_url('/client-portal/');return $redirect_to;}add_filter('login_redirect','legacyx_client_login_redirect',10,3);
/* Client wp-admin restrictions are enforced centrally in roles-permissions.php. */
function legacyx_client_account_metabox(){if(current_user_can('legacyx_manage_clients'))add_meta_box('legacyx_client_account','Client Portal Account','legacyx_render_client_account_box','legacyx_client','side','high');}add_action('add_meta_boxes','legacyx_client_account_metabox');
function legacyx_render_client_account_box($post){
    if(!current_user_can('legacyx_manage_clients'))return;
    $uid=absint(get_post_meta($post->ID,'_legacyx_wp_user_id',true));$email=sanitize_email(get_post_meta($post->ID,'_legacyx_email',true));
    wp_nonce_field('legacyx_assign_client_account_'.$post->ID,'legacyx_assign_client_account_nonce');
    if($uid){$user=get_userdata($uid);if($user)update_user_meta($uid,'_legacyx_client_profile_id',$post->ID);echo '<p><strong>Connected:</strong><br>'.esc_html($user?$user->user_login:'User #'.$uid).'</p><p><strong>Email:</strong><br>'.esc_html($user?$user->user_email:$email).'</p>';}else echo '<p><strong>Status:</strong> No client account connected.</p>';
    $users=get_users(array('orderby'=>'user_login','order'=>'ASC'));echo '<p><label for="legacyx_assign_user"><strong>Assign existing client account</strong></label><select id="legacyx_assign_user" name="legacyx_assign_user" style="width:100%;margin-top:6px"><option value="">Select account</option>';
    foreach($users as $candidate){if(array_intersect(array('administrator','legacyx_advisor','legacyx_manager'),(array)$candidate->roles))continue;echo '<option value="'.esc_attr($candidate->ID).'" '.selected($uid,$candidate->ID,false).'>'.esc_html($candidate->user_login.' · '.$candidate->user_email).'</option>';}echo '</select></p><p><button type="submit" class="button button-primary" name="legacyx_assign_client_account" value="1">Connect Selected Account</button></p><p><small>Connecting an account assigns the Legacy X Client role and links it to this Universal Client Profile.</small></p>';
    if(!$uid&&$email){wp_nonce_field('legacyx_create_client_account_'.$post->ID,'legacyx_client_account_nonce');echo '<hr><p><button type="submit" class="button" name="legacyx_create_client_account" value="1">Create Client Account</button></p>';}
}
function legacyx_assign_existing_client_account($post_id){if(get_post_type($post_id)!=='legacyx_client'||empty($_POST['legacyx_assign_client_account'])||!current_user_can('legacyx_manage_clients'))return;if(!current_user_can('edit_post',$post_id)||!isset($_POST['legacyx_assign_client_account_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['legacyx_assign_client_account_nonce'])),'legacyx_assign_client_account_'.$post_id))return;$uid=absint($_POST['legacyx_assign_user']??0);if(!$uid)return;$user=get_userdata($uid);if(!$user||array_intersect(array('administrator','legacyx_advisor','legacyx_manager'),(array)$user->roles))return;$old=absint(get_post_meta($post_id,'_legacyx_wp_user_id',true));if($old&&$old!==$uid)delete_user_meta($old,'_legacyx_client_profile_id',$post_id);$other=absint(get_user_meta($uid,'_legacyx_client_profile_id',true));if($other&&$other!==$post_id)delete_post_meta($other,'_legacyx_wp_user_id',$uid);$user->set_role('legacyx_client');update_post_meta($post_id,'_legacyx_wp_user_id',$uid);update_user_meta($uid,'_legacyx_client_profile_id',$post_id);}add_action('save_post_legacyx_client','legacyx_assign_existing_client_account',30);
function legacyx_create_client_account_from_profile($post_id){if(get_post_type($post_id)!=='legacyx_client'||empty($_POST['legacyx_create_client_account'])||!current_user_can('legacyx_manage_clients'))return;if(!current_user_can('edit_post',$post_id)||!isset($_POST['legacyx_client_account_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['legacyx_client_account_nonce'])),'legacyx_create_client_account_'.$post_id))return;$current=absint(get_post_meta($post_id,'_legacyx_wp_user_id',true));if($current){update_user_meta($current,'_legacyx_client_profile_id',$post_id);return;}$email=sanitize_email(get_post_meta($post_id,'_legacyx_email',true));if(!$email||!is_email($email))return;$existing=get_user_by('email',$email);if($existing){if(array_intersect(array('administrator','legacyx_advisor','legacyx_manager'),(array)$existing->roles))return;$uid=$existing->ID;$existing->set_role('legacyx_client');}else{$base=sanitize_user(strtolower(strstr($email,'@',true)),true);if(!$base)$base='legacyxclient';$login=$base;$i=1;while(username_exists($login)){$login=$base.$i;$i++;}$uid=wp_create_user($login,wp_generate_password(32,true,true),$email);if(is_wp_error($uid))return;$user=new WP_User($uid);$user->set_role('legacyx_client');wp_new_user_notification($uid,null,'user');}update_post_meta($post_id,'_legacyx_wp_user_id',absint($uid));update_user_meta($uid,'_legacyx_client_profile_id',$post_id);}add_action('save_post_legacyx_client','legacyx_create_client_account_from_profile',20);
function legacyx_repair_client_link_on_login($user_login,$user){if(!$user instanceof WP_User||!in_array('legacyx_client',(array)$user->roles,true))return;if(absint(get_user_meta($user->ID,'_legacyx_client_profile_id',true)))return;$email=sanitize_email($user->user_email);if(!$email)return;$matches=get_posts(array('post_type'=>'legacyx_client','post_status'=>'any','numberposts'=>2,'meta_key'=>'_legacyx_email','meta_value'=>$email));if(count($matches)!==1)return;$client=$matches[0];$linked=absint(get_post_meta($client->ID,'_legacyx_wp_user_id',true));if($linked&&$linked!==$user->ID)return;update_post_meta($client->ID,'_legacyx_wp_user_id',$user->ID);update_user_meta($user->ID,'_legacyx_client_profile_id',$client->ID);}add_action('wp_login','legacyx_repair_client_link_on_login',10,2);
