<?php
if(!defined('ABSPATH'))exit;
function legacyx_register_engagement_type(){register_post_type('legacyx_engagement',array('labels'=>array('name'=>'Services & Engagements','singular_name'=>'Engagement','add_new_item'=>'Add Engagement','edit_item'=>'Edit Engagement','menu_name'=>'Services'),'public'=>false,'show_ui'=>true,'show_in_menu'=>true,'menu_icon'=>'dashicons-portfolio','supports'=>array('title'),'show_in_rest'=>false,'capability_type'=>'post','map_meta_cap'=>true));}add_action('init','legacyx_register_engagement_type');
function legacyx_engagement_boxes(){add_meta_box('legacyx_engagement_details','Service Engagement','legacyx_render_engagement_box','legacyx_engagement','normal','high');}add_action('add_meta_boxes','legacyx_engagement_boxes');
function legacyx_engagement_field($post,$key,$label,$type='text'){$v=get_post_meta($post->ID,'_legacyx_'.$key,true);echo '<p><label><strong>'.esc_html($label).'</strong></label><br><input type="'.esc_attr($type).'" name="legacyx_'.esc_attr($key).'" value="'.esc_attr($v).'" style="width:100%"></p>';}
function legacyx_engagement_area($post,$key,$label){$v=get_post_meta($post->ID,'_legacyx_'.$key,true);echo '<p><label><strong>'.esc_html($label).'</strong></label><br><textarea name="legacyx_'.esc_attr($key).'" style="width:100%;min-height:90px">'.esc_textarea($v).'</textarea></p>';}
function legacyx_engagement_select($key,$label,$value,$opts){echo '<p><label><strong>'.esc_html($label).'</strong></label><br><select name="legacyx_'.esc_attr($key).'" style="width:100%"><option value="">Select</option>';foreach($opts as $o)echo '<option value="'.esc_attr($o).'" '.selected($value,$o,false).'>'.esc_html($o).'</option>';echo '</select></p>';}
function legacyx_render_engagement_box($post){wp_nonce_field('legacyx_save_engagement','legacyx_engagement_nonce');$client_id=absint(get_post_meta($post->ID,'_legacyx_client_id',true));$clients=get_posts(array('post_type'=>'legacyx_client','post_status'=>'any','numberposts'=>-1,'orderby'=>'title','order'=>'ASC'));echo '<p><label><strong>Universal Client Profile</strong></label><br><select name="legacyx_client_id" style="width:100%"><option value="">Select client</option>';foreach($clients as $c){$code=get_post_meta($c->ID,'_legacyx_client_id',true);echo '<option value="'.esc_attr($c->ID).'" '.selected($client_id,$c->ID,false).'>'.esc_html($c->post_title.' · '.$code).'</option>';}echo '</select></p>';$division=get_post_meta($post->ID,'_legacyx_division',true);$level=get_post_meta($post->ID,'_legacyx_delivery_level',true);$status=get_post_meta($post->ID,'_legacyx_engagement_status',true);legacyx_engagement_select('division','Service Division',$division,array('Credit & Capital','Business Advisory','Financial Advisory','Tax & Compliance','Grants & Organizational Development','Private Advisory','Legacy X Firm Academy','Legacy X Intelligence','Other'));legacyx_engagement_select('delivery_level','Delivery Level',$level,array('Self-Service','Guided','Done-for-You','Private Advisory'));legacyx_engagement_select('engagement_status','Engagement Status',$status,array('Proposed','Onboarding','Active','Waiting on Client','On Hold','Completed','Cancelled'));legacyx_engagement_field($post,'advisor','Lead Advisor');legacyx_engagement_field($post,'start_date','Start Date','date');legacyx_engagement_field($post,'target_date','Target Completion','date');legacyx_engagement_field($post,'fee','Engagement Fee / Retainer');legacyx_engagement_area($post,'objective','Primary Objective');legacyx_engagement_area($post,'deliverables','Deliverables');legacyx_engagement_area($post,'next_action','Next Recommended Action');}
function legacyx_save_engagement($id){if(get_post_type($id)!=='legacyx_engagement')return;if(!isset($_POST['legacyx_engagement_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['legacyx_engagement_nonce'])),'legacyx_save_engagement'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!current_user_can('edit_post',$id))return;update_post_meta($id,'_legacyx_client_id',absint($_POST['legacyx_client_id']??0));foreach(array('division','delivery_level','engagement_status','advisor','start_date','target_date','fee') as $k)update_post_meta($id,'_legacyx_'.$k,sanitize_text_field(wp_unslash($_POST['legacyx_'.$k]??'')));foreach(array('objective','deliverables','next_action') as $k)update_post_meta($id,'_legacyx_'.$k,sanitize_textarea_field(wp_unslash($_POST['legacyx_'.$k]??'')));}add_action('save_post_legacyx_engagement','legacyx_save_engagement');
function legacyx_get_client_engagements($client_id){return get_posts(array('post_type'=>'legacyx_engagement','post_status'=>'any','numberposts'=>-1,'meta_key'=>'_legacyx_client_id','meta_value'=>absint($client_id),'orderby'=>'date','order'=>'DESC'));}
function legacyx_engagement_counts($client_id){$rows=legacyx_get_client_engagements($client_id);$out=array('total'=>count($rows),'active'=>0,'completed'=>0);foreach($rows as $r){$s=get_post_meta($r->ID,'_legacyx_engagement_status',true);if(in_array($s,array('Onboarding','Active','Waiting on Client'),true))$out['active']++;if($s==='Completed')$out['completed']++;}return $out;}
