<?php
if(!defined('ABSPATH'))exit;
function legacyx_executive_briefing_data(){
 if(!function_exists('legacyx_intelligence_snapshot'))return array();
 $firm=legacyx_intelligence_snapshot();list($band)=legacyx_intelligence_band($firm['overall']);
 $watch=function_exists('legacyx_client_intelligence_watchlist_data')?legacyx_client_intelligence_watchlist_data(100):array();
 $counts=array('Priority'=>0,'Watch'=>0,'Stable'=>0,'Strong'=>0);foreach($watch as $r)if(isset($counts[$r['priority']]))$counts[$r['priority']]++;
 $history=function_exists('legacyx_intelligence_trend_data')?legacyx_intelligence_trend_data(30):array();$movement='Building baseline';$delta=0;
 if(count($history)>1){$dates=array_keys($history);$latest=end($history);$prev=$history[$dates[count($dates)-2]];list($movement,$delta)=legacyx_intelligence_movement($latest['average'],$prev['average']);}
 return array('firm'=>$firm,'band'=>$band,'counts'=>$counts,'movement'=>$movement,'delta'=>$delta,'actions'=>legacyx_intelligence_recommendations($firm),'top'=>array_slice($watch,0,3));
}
function legacyx_render_executive_briefing(){if(!current_user_can('legacyx_view_reports'))return;$d=legacyx_executive_briefing_data();if(!$d)return;$f=$d['firm'];?>
<section class="lxi-brief"><div class="lxi-brief-head"><div><span>EXECUTIVE BRIEFING</span><h2>Management Intelligence Brief</h2><p>Current Firm OS operating signals, relationship posture, movement and immediate management focus.</p></div><div><small>Firm Posture</small><strong><?php echo esc_html($d['band']);?></strong><em><?php echo esc_html($f['overall']);?> / 100</em></div></div><div class="lxi-brief-strip"><div><span>Movement</span><strong><?php echo esc_html($d['movement']);?></strong><small><?php echo esc_html(($d['delta']>0?'+':'').$d['delta']);?> pts</small></div><div><span>Priority Relationships</span><strong><?php echo esc_html($d['counts']['Priority']);?></strong></div><div><span>Watch Relationships</span><strong><?php echo esc_html($d['counts']['Watch']);?></strong></div><div><span>Attention Signals</span><strong><?php echo esc_html(count($f['signals']));?></strong></div><div><span>Outstanding Records</span><strong><?php echo esc_html(function_exists('legacyx_money')?legacyx_money($f['outstanding']):number_format($f['outstanding'],2));?></strong></div></div><div class="lxi-brief-grid"><div><h3>Immediate Management Focus</h3><?php foreach(array_slice($d['actions'],0,4) as $i=>$a):?><article><b><?php echo esc_html(sprintf('%02d',$i+1));?></b><div><strong><?php echo esc_html($a[0]);?></strong><p><?php echo esc_html($a[1]);?></p></div></article><?php endforeach;?></div><aside><h3>Relationships to Review</h3><?php if(!$d['top']):?><p>No client relationship intelligence is available yet.</p><?php else:foreach($d['top'] as $r):$url=add_query_arg(array('page'=>'legacyx-client-360','client_id'=>$r['id']),admin_url('admin.php'));?><a href="<?php echo esc_url($url);?>"><span><strong><?php echo esc_html($r['name']);?></strong><small><?php echo esc_html($r['priority']);?> posture</small></span><b><?php echo esc_html($r['score']);?></b></a><?php endforeach;endif;?></aside></div><div class="lxi-brief-footer"><span>Generated from current Legacy X Firm OS records</span><a href="<?php echo esc_url(admin_url('admin.php?page=legacyx-intelligence'));?>">Open Full Intelligence →</a></div><small class="lxi-brief-boundary">Internal executive management aid. Heuristic operating signals only; not audited financial analysis, legal advice, credit or underwriting decisions, investment advice, guarantees or predictions.</small></section>
<?php }
function legacyx_executive_briefing_inject(){if(!current_user_can('legacyx_view_reports'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='toplevel_page_legacyx-firm-os')return;ob_start();legacyx_render_executive_briefing();$html=ob_get_clean();if(!$html)return;?><div id="legacyx-brief-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var src=document.getElementById('legacyx-brief-source'),metrics=document.querySelector('.legacyx-staff-metrics');if(src&&metrics){var w=document.createElement('div');w.innerHTML=src.innerHTML;metrics.insertAdjacentElement('afterend',w.firstElementChild);src.remove();}});</script><?php }
add_action('admin_footer','legacyx_executive_briefing_inject',8);
function legacyx_executive_briefing_styles($hook){if($hook!=='toplevel_page_legacyx-firm-os')return;wp_register_style('legacyx-executive-briefing',false);wp_enqueue_style('legacyx-executive-briefing');$css='.lxi-brief{background:#f7f4ed;border:1px solid #d9d2c7;padding:30px;margin-top:18px;color:#171512}.lxi-brief-head{display:flex;justify-content:space-between;gap:30px;align-items:end}.lxi-brief-head>div:first-child span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxi-brief-head h2{font:32px Georgia,serif;margin:5px 0 8px}.lxi-brief-head p{color:#6d675f;max-width:780px;margin:0}.lxi-brief-head>div:last-child{text-align:right}.lxi-brief-head small,.lxi-brief-head em{display:block;color:#746e65}.lxi-brief-head strong{display:block;font:30px Georgia,serif}.lxi-brief-head em{font-style:normal}.lxi-brief-strip{display:grid;grid-template-columns:repeat(5,1fr);background:#171512;color:#fff;margin-top:24px}.lxi-brief-strip>div{padding:17px;border-right:1px solid #3a3631}.lxi-brief-strip span,.lxi-brief-strip small{display:block;color:#aaa197}.lxi-brief-strip strong{font:22px Georgia,serif;display:block;margin-top:4px}.lxi-brief-grid{display:grid;grid-template-columns:2fr 1fr;gap:20px;margin-top:24px}.lxi-brief-grid h3{font:23px Georgia,serif}.lxi-brief-grid article{display:flex;gap:14px;padding:14px 0;border-top:1px solid #ddd6cb}.lxi-brief-grid article>b{color:#f05a16;font:20px Georgia,serif}.lxi-brief-grid article p{color:#6d675f;margin:4px 0}.lxi-brief-grid aside{background:#fff;padding:20px;border:1px solid #ddd6cb}.lxi-brief-grid aside>a{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-top:1px solid #e7e1d8;color:#171512;text-decoration:none}.lxi-brief-grid aside small{display:block;color:#746e65}.lxi-brief-grid aside>a>b{font:24px Georgia,serif;color:#f05a16}.lxi-brief-footer{display:flex;justify-content:space-between;border-top:1px solid #d9d2c7;padding-top:16px;margin-top:18px;color:#746e65}.lxi-brief-footer a{color:#171512;font-weight:800;text-decoration:none}.lxi-brief-boundary{display:block;color:#8a837a;margin-top:12px}@media(max-width:900px){.lxi-brief-strip{grid-template-columns:repeat(2,1fr)}.lxi-brief-grid{grid-template-columns:1fr}}@media(max-width:600px){.lxi-brief-head,.lxi-brief-footer{display:block}.lxi-brief-head>div:last-child{text-align:left;margin-top:18px}.lxi-brief-strip{grid-template-columns:1fr}.lxi-brief-footer a{display:block;margin-top:10px}}';wp_add_inline_style('legacyx-executive-briefing',$css);}add_action('admin_enqueue_scripts','legacyx_executive_briefing_styles');
