<?php
if(!defined('ABSPATH'))exit;
function legacyx_intelligence_history_key(){return 'legacyx_intelligence_history_v1';}
function legacyx_intelligence_history(){ $h=get_option(legacyx_intelligence_history_key(),array());return is_array($h)?$h:array(); }
function legacyx_intelligence_capture_history(){
 if(!function_exists('legacyx_client_intelligence_snapshot'))return;
 $today=current_time('Y-m-d');$history=legacyx_intelligence_history();if(isset($history[$today]))return;
 $clients=get_posts(array('post_type'=>'legacyx_client','post_status'=>'any','numberposts'=>200,'fields'=>'ids'));
 $scores=array();$postures=array('Priority'=>0,'Watch'=>0,'Stable'=>0,'Strong'=>0);
 foreach($clients as $id){$s=legacyx_client_intelligence_snapshot($id);if(!$s)continue;$scores[]=(int)$s['overall'];if(isset($postures[$s['priority']]))$postures[$s['priority']]++;}
 $avg=$scores?(int)round(array_sum($scores)/count($scores)):0;
 $history[$today]=array('average'=>$avg,'clients'=>count($scores),'postures'=>$postures,'captured'=>current_time('mysql'));
 if(count($history)>180)$history=array_slice($history,-180,null,true);update_option(legacyx_intelligence_history_key(),$history,false);
}
add_action('admin_init','legacyx_intelligence_capture_history',30);
function legacyx_intelligence_movement($current,$previous){$delta=(int)$current-(int)$previous;if($delta>=3)return array('Improving',$delta);if($delta<=-3)return array('Declining',$delta);return array('Stable',$delta);}
function legacyx_intelligence_trend_data($days=30){$history=legacyx_intelligence_history();$cutoff=date('Y-m-d',current_time('timestamp')-($days*DAY_IN_SECONDS));$rows=array();foreach($history as $date=>$row)if($date>=$cutoff)$rows[$date]=$row;return $rows;}
function legacyx_render_intelligence_trends(){if(!current_user_can('legacyx_manage_clients'))return;$history=legacyx_intelligence_trend_data(30);if(!$history)return;$dates=array_keys($history);$latest=end($history);$previous=count($history)>1?$history[$dates[count($dates)-2]]:$latest;list($movement,$delta)=legacyx_intelligence_movement($latest['average'],$previous['average']);$max=max(1,max(array_map(function($r){return (int)$r['average'];},$history)));?>
<section class="lxi-trends"><div class="lxi-trend-head"><div><span>INTELLIGENCE MOVEMENT</span><h2>Relationship Portfolio Trend</h2><p>Daily snapshots show whether the client portfolio's recorded operating posture is improving, declining, or holding steady.</p></div><div class="lxi-movement <?php echo esc_attr(strtolower($movement));?>"><small>Current Movement</small><strong><?php echo esc_html($movement);?></strong><em><?php echo esc_html(($delta>0?'+':'').$delta);?> pts</em></div></div><div class="lxi-trend-chart"><?php foreach($history as $date=>$row):$height=max(4,round(((int)$row['average']/$max)*100));?><div class="lxi-trend-bar" title="<?php echo esc_attr(date_i18n('M j',strtotime($date)).' · '.$row['average']);?>"><i style="height:<?php echo esc_attr($height);?>%"></i><span><?php echo esc_html(date_i18n('M j',strtotime($date)));?></span></div><?php endforeach;?></div><div class="lxi-trend-summary"><div><span>Portfolio Score</span><strong><?php echo esc_html($latest['average']);?></strong></div><div><span>Relationships</span><strong><?php echo esc_html($latest['clients']);?></strong></div><div><span>Priority</span><strong><?php echo esc_html($latest['postures']['Priority']??0);?></strong></div><div><span>Watch</span><strong><?php echo esc_html($latest['postures']['Watch']??0);?></strong></div><div><span>Strong</span><strong><?php echo esc_html($latest['postures']['Strong']??0);?></strong></div></div><small class="lxi-trend-boundary">Movement reflects changes in Legacy X Firm OS records and heuristic relationship scores. It is an internal operational trend, not a financial performance measure or prediction.</small></section>
<?php }
function legacyx_intelligence_trends_inject(){if(!current_user_can('legacyx_manage_clients'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='toplevel_page_legacyx-firm-os')return;ob_start();legacyx_render_intelligence_trends();$html=ob_get_clean();if(!$html)return;?><div id="legacyx-trends-source" style="display:none"><?php echo $html;?></div><script>document.addEventListener('DOMContentLoaded',function(){var src=document.getElementById('legacyx-trends-source'),watch=document.querySelector('.lxi-watchlist');if(src&&watch){var w=document.createElement('div');w.innerHTML=src.innerHTML;watch.insertAdjacentElement('afterend',w.firstElementChild);src.remove();}});</script><?php }
add_action('admin_footer','legacyx_intelligence_trends_inject',25);
function legacyx_intelligence_trends_styles($hook){if($hook!=='toplevel_page_legacyx-firm-os')return;wp_register_style('legacyx-intelligence-trends',false);wp_enqueue_style('legacyx-intelligence-trends');$css='.lxi-trends{background:#171512;color:#fff;padding:28px;margin-top:18px}.lxi-trend-head{display:flex;justify-content:space-between;gap:24px;align-items:end}.lxi-trend-head>div>span{font-size:11px;font-weight:800;letter-spacing:.16em;color:#f05a16}.lxi-trend-head h2{font:29px Georgia,serif;margin:5px 0 8px}.lxi-trend-head p{color:#c9c3ba;max-width:760px;margin:0}.lxi-movement{text-align:right}.lxi-movement small,.lxi-movement em{display:block;color:#aaa197}.lxi-movement strong{display:block;font:28px Georgia,serif;color:#f05a16}.lxi-movement em{font-style:normal}.lxi-trend-chart{height:190px;display:flex;gap:5px;align-items:end;border-bottom:1px solid #4b4640;margin-top:28px;padding:0 4px}.lxi-trend-bar{flex:1;height:150px;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;min-width:4px}.lxi-trend-bar i{display:block;width:100%;max-width:28px;background:#f05a16;min-height:4px}.lxi-trend-bar span{font-size:9px;color:#9f978d;margin-top:8px;white-space:nowrap}.lxi-trend-summary{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid #393631;margin-top:24px}.lxi-trend-summary>div{padding:16px;border-right:1px solid #393631}.lxi-trend-summary span{display:block;color:#aaa197}.lxi-trend-summary strong{font:25px Georgia,serif}.lxi-trend-boundary{display:block;color:#8f877d;margin-top:16px}@media(max-width:700px){.lxi-trend-head{display:block}.lxi-movement{text-align:left;margin-top:18px}.lxi-trend-summary{grid-template-columns:repeat(2,1fr)}.lxi-trend-bar span{display:none}}';wp_add_inline_style('legacyx-intelligence-trends',$css);}add_action('admin_enqueue_scripts','legacyx_intelligence_trends_styles');
