<?php
if(!defined('ABSPATH'))exit;
function legacyx_report_date_value($key){$v=sanitize_text_field(wp_unslash($_GET[$key]??''));return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)?$v:'';}
function legacyx_report_date_args($from='',$to=''){if(!$from&&!$to)return array();$row=array('inclusive'=>true,'column'=>'post_date');if($from)$row['after']=$from.' 00:00:00';if($to)$row['before']=$to.' 23:59:59';return array($row);}
function legacyx_report_ids_in_range($type,$from='',$to=''){return get_posts(array('post_type'=>$type,'post_status'=>'any','numberposts'=>-1,'fields'=>'ids','orderby'=>'date','order'=>'DESC','date_query'=>legacyx_report_date_args($from,$to)));}
function legacyx_report_csv_cell($value){if(is_array($value))$value=implode(' | ',$value);$value=(string)$value;return preg_replace('/^[=+\-@]/','\'$0',$value);}
function legacyx_report_csv_download($filename,$headers,$rows){nocache_headers();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.sanitize_file_name($filename).'"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,array_map('legacyx_report_csv_cell',$headers));foreach($rows as $row)fputcsv($out,array_map('legacyx_report_csv_cell',$row));fclose($out);exit;}
function legacyx_export_executive_report(){if(!current_user_can('legacyx_view_reports'))wp_die('You do not have access to Legacy X Firm reports.','Legacy X Firm',array('response'=>403));check_admin_referer('legacyx_export_report');$from=legacyx_report_date_value('from');$to=legacyx_report_date_value('to');$dataset=sanitize_key(wp_unslash($_GET['dataset']??'summary'));$stamp=current_time('Y-m-d');
 if($dataset==='clients'){$rows=array();foreach(legacyx_report_ids_in_range('legacyx_client',$from,$to) as $id)$rows[]=array(get_post_meta($id,'_legacyx_client_id',true),get_the_title($id),get_post_meta($id,'_legacyx_business_name',true),get_post_meta($id,'_legacyx_status',true),get_post_meta($id,'_legacyx_service_level',true),get_the_date('Y-m-d',$id));legacyx_report_csv_download('legacy-x-client-growth-'.$stamp.'.csv',array('Client ID','Client','Business','Status','Service Level','Created'),$rows);}
 if($dataset==='divisions'){$rows=array();foreach(legacyx_reports_divisions() as $division=>$d)$rows[]=array($division,$d['total'],$d['active'],$d['fee']);legacyx_report_csv_download('legacy-x-division-performance-'.$stamp.'.csv',array('Division','Engagements','Active','Recorded Engagement Fees'),$rows);}
 if($dataset==='applications'){$rows=array();foreach(legacyx_report_ids_in_range('legacyx_application',$from,$to) as $id)$rows[]=array($id,get_the_title($id),get_post_meta($id,'_legacyx_status',true),get_post_meta($id,'_legacyx_client_id',true),get_the_date('Y-m-d',$id));legacyx_report_csv_download('legacy-x-application-pipeline-'.$stamp.'.csv',array('Application ID','Application','Status','Client Profile ID','Created'),$rows);}
 if($dataset==='billing'){$rows=array();foreach(legacyx_report_ids_in_range('legacyx_invoice',$from,$to) as $id){$amount=(float)get_post_meta($id,'_legacyx_amount',true);$paid=(float)get_post_meta($id,'_legacyx_paid_amount',true);$rows[]=array(get_post_meta($id,'_legacyx_invoice_number',true)?:$id,get_the_title($id),get_post_meta($id,'_legacyx_status',true),$amount,$paid,max(0,$amount-$paid),get_the_date('Y-m-d',$id));}legacyx_report_csv_download('legacy-x-recorded-billing-'.$stamp.'.csv',array('Invoice','Record','Status','Recorded Amount','Recorded Paid','Outstanding','Created'),$rows);}
 $rows=array(array('Report Period',$from?:'All time',$to?:'Current'),array('Client Relationships',legacyx_reports_count('legacyx_client'),'',''),array('Applications',legacyx_reports_count('legacyx_application'),'',''),array('Workflow Items',legacyx_reports_count('legacyx_work_item'),'',''),array('Engagements',legacyx_reports_count('legacyx_engagement'),'',''),array('Invoices',legacyx_reports_count('legacyx_invoice'),'',''));legacyx_report_csv_download('legacy-x-executive-summary-'.$stamp.'.csv',array('Metric','Value','Notes',''),$rows);
}add_action('admin_post_legacyx_export_report','legacyx_export_executive_report');
function legacyx_reports_controls(){if(!current_user_can('legacyx_view_reports'))return;$from=legacyx_report_date_value('from');$to=legacyx_report_date_value('to');$base=admin_url('admin.php');echo '<div class="legacyx-report-controls"><form method="get"><input type="hidden" name="page" value="legacyx-reports"><label>From <input type="date" name="from" value="'.esc_attr($from).'"></label><label>To <input type="date" name="to" value="'.esc_attr($to).'"></label><button class="button button-primary">Apply Range</button><a class="button" href="'.esc_url(add_query_arg('page','legacyx-reports',$base)).'">Reset</a></form><div class="legacyx-export-links">';foreach(array('summary'=>'Executive Summary','clients'=>'Client Growth','divisions'=>'Division Performance','applications'=>'Application Pipeline','billing'=>'Recorded Billing') as $key=>$label){$url=wp_nonce_url(add_query_arg(array('action'=>'legacyx_export_report','dataset'=>$key,'from'=>$from,'to'=>$to),admin_url('admin-post.php')),'legacyx_export_report');echo '<a class="button" href="'.esc_url($url).'">Export '.esc_html($label).'</a>';}echo '</div></div>';}
