<?php
if(!defined('ABSPATH'))exit;
if(!is_user_logged_in()){wp_safe_redirect(wp_login_url(home_url('/applications-center/')));exit;}
$client=legacyx_find_client_by_wp_user(get_current_user_id());
$app_id=absint(get_query_var('legacyx_application_id'));
$app=$app_id?get_post($app_id):null;
$authorized=$client&&$app&&$app->post_type==='legacyx_application'&&(int)get_post_meta($app_id,'_legacyx_client_id',true)===(int)$client->ID;
if(!$authorized){status_header(404);nocache_headers();get_header();echo '<main class="legacyx-credit-center"><div class="legacyx-credit-shell"><a class="legacyx-credit-back" href="'.esc_url(home_url('/applications-center/')).'">← Applications Center</a><section class="legacyx-credit-track"><div class="legacyx-track-title"><span>PRIVATE APPLICATION</span><h1>Application not available</h1><p>This application is not connected to your Universal Client Profile.</p></div></section></div></main>';get_footer();exit;}
$type=get_post_meta($app_id,'_legacyx_type',true);$status=get_post_meta($app_id,'_legacyx_status',true);$amount=get_post_meta($app_id,'_legacyx_requested_amount',true);$provider=get_post_meta($app_id,'_legacyx_provider',true);$deadline=get_post_meta($app_id,'_legacyx_deadline',true);$decision=get_post_meta($app_id,'_legacyx_decision',true);$docs=get_post_meta($app_id,'_legacyx_required_documents',true);$note=get_post_meta($app_id,'_legacyx_advisor_note',true);
get_header(); ?>
<main class="legacyx-credit-center"><div class="legacyx-credit-shell"><a class="legacyx-credit-back" href="<?php echo esc_url(home_url('/applications-center/'));?>">← Applications Center</a><header class="legacyx-credit-head"><div><span class="kicker">LEGACY X FIRM OS · APPLICATION DETAIL</span><h1><?php echo esc_html(get_the_title($app));?></h1><p>Private application record connected to your Universal Client Profile.</p></div><div class="legacyx-credit-identity"><span>Status</span><strong><?php echo esc_html($status?:'Pending');?></strong><small><?php echo esc_html(get_post_meta($client->ID,'_legacyx_client_id',true));?></small></div></header><section class="legacyx-credit-summary"><div><span>Type</span><strong><?php echo esc_html($type?:'Not specified');?></strong></div><div><span>Requested Amount</span><strong><?php echo esc_html($amount?:'—');?></strong></div><div><span>Deadline</span><strong><?php echo esc_html($deadline?:'—');?></strong></div><div><span>Decision</span><strong><?php echo esc_html($decision?:'Pending');?></strong></div></section><section class="legacyx-credit-track"><div class="legacyx-track-title"><span>APPLICATION RECORD</span><h2>Application Details</h2></div><div class="legacyx-step-list"><article class="legacyx-credit-step"><span class="legacyx-step-num">01</span><div><h3>Provider / Program</h3><p><?php echo esc_html($provider?:'Not specified');?></p></div></article><article class="legacyx-credit-step"><span class="legacyx-step-num">02</span><div><h3>Required Documents</h3><p><?php echo nl2br(esc_html($docs?:'No document requirements have been added yet.'));?></p></div></article><article class="legacyx-credit-step"><span class="legacyx-step-num">03</span><div><h3>Advisor Next Action</h3><p><?php echo nl2br(esc_html($note?:'No advisor action has been added yet.'));?></p></div></article></div></section><section class="legacyx-credit-action"><span>Privacy</span><p>This record is available only to the WordPress client account connected to this Universal Client Profile and authorized Legacy X Firm staff.</p></section></div></main>
<?php get_footer();