<?php
if (!defined('ABSPATH')) exit;
get_header();
$current_user=wp_get_current_user();$portal_url=home_url('/client-portal/');$client=is_user_logged_in()?legacyx_find_client_by_wp_user(get_current_user_id()):null;$client_id=$client?get_post_meta($client->ID,'_legacyx_client_id',true):'';$status=$client?get_post_meta($client->ID,'_legacyx_status',true):'';$business=$client?get_post_meta($client->ID,'_legacyx_business_name',true):'';$service_level=$client?get_post_meta($client->ID,'_legacyx_service_level',true):'';$capital_goal=$client?get_post_meta($client->ID,'_legacyx_capital_goal',true):'';$creditos=$client?legacyx_creditos_get_client_data($client->ID):legacyx_creditos_defaults();
?>
<main id="legacyx-client-portal" class="legacyx-portal"><section><div class="legacyx-portal-shell"><div class="legacyx-portal-brand"><span class="kicker">LEGACY X FIRM OS</span><h1>Client Command Center</h1><p>One private workspace for your Legacy X Firm relationship, services, strategic progress and support.</p></div>
<?php if(!is_user_logged_in()): ?><div class="legacyx-login-card"><h2>Welcome Back</h2><p>Sign in to access your private client workspace.</p><?php wp_login_form(array('echo'=>true,'redirect'=>$portal_url,'form_id'=>'legacyx-loginform','label_username'=>'Email or Username','label_password'=>'Password','label_remember'=>'Remember Me','label_log_in'=>'Sign In','remember'=>true)); ?><div class="legacyx-login-links"><a href="<?php echo esc_url(wp_lostpassword_url($portal_url)); ?>">Forgot your password?</a></div><div class="legacyx-support-note"><strong>Need help accessing your account?</strong><br><a href="mailto:info@legacyxfirm.us">info@legacyxfirm.us</a></div></div>
<?php else: ?><div class="legacyx-dashboard-wrap"><div class="legacyx-dashboard-topbar"><div><span class="kicker">PRIVATE CLIENT WORKSPACE</span><h2>Welcome, <?php echo esc_html($current_user->display_name?:$current_user->user_login); ?></h2><p><?php echo $client?'Your Universal Client Profile is connected to this account.':'Your portal account is active. Your advisory profile is awaiting connection.'; ?></p></div><a class="legacyx-logout-button" href="<?php echo esc_url(wp_logout_url($portal_url)); ?>">Log Out</a></div>
<?php if($client): ?><div class="legacyx-profile-strip"><div><span>Client ID</span><strong><?php echo esc_html($client_id); ?></strong></div><div><span>Relationship</span><strong><?php echo esc_html($status?:'Active'); ?></strong></div><div><span>Primary Business</span><strong><?php echo esc_html($business?:'Not yet recorded'); ?></strong></div><div><span>Service Level</span><strong><?php echo esc_html($service_level?:'Advisory'); ?></strong></div></div><?php else: ?><div class="legacyx-portal-notice"><strong>Profile connection pending.</strong> Your Legacy X Firm team can connect this login to your Universal Client Profile from the private administration console.</div><?php endif; ?>
<div class="legacyx-dashboard-grid"><article class="legacyx-dashboard-card"><span class="legacyx-card-number">01</span><h3>Strategic Overview</h3><p><?php echo $client?'Your central relationship record is active and ready to coordinate every Legacy X Firm module.':'Your strategic overview will appear once your client profile is connected.'; ?></p><span class="legacyx-coming-soon"><?php echo $capital_goal?'Capital objective: '.esc_html($capital_goal):'Universal profile'; ?></span></article>
<article class="legacyx-dashboard-card"><span class="legacyx-card-number">02</span><h3>My Services</h3><p>View advisory engagements and services associated with your relationship.</p><span class="legacyx-coming-soon">Service workspace next</span></article>
<article class="legacyx-dashboard-card legacyx-creditos-card"><span class="legacyx-card-number">03 · CREDITOS</span><h3>Credit & Capital</h3><?php if($client): ?><p><strong>Personal:</strong> <?php echo esc_html($creditos['personal_stage']); ?><br><strong>Business:</strong> <?php echo esc_html($creditos['business_stage']); ?><br><strong>Funding Goal:</strong> <?php echo esc_html($creditos['funding_goal']?:($capital_goal?:'Not yet set')); ?></p><span class="legacyx-coming-soon"><?php echo esc_html($creditos['next_action']); ?></span><?php else: ?><p>Your Personal Credit, Business Credit and Funding Readiness tracks will appear when your profile is connected.</p><span class="legacyx-coming-soon">7 steps personal · 7 steps business</span><?php endif; ?></article>
<article class="legacyx-dashboard-card"><span class="legacyx-card-number">04</span><h3>Business Center</h3><p>Organize entities, ownership, operations and business strategy from one workspace.</p><span class="legacyx-coming-soon">Business module</span></article><article class="legacyx-dashboard-card"><span class="legacyx-card-number">05</span><h3>Documents & Tasks</h3><p>Secure documents, required actions, checklists and progress items will be coordinated here.</p><span class="legacyx-coming-soon">Workflow module</span></article><article class="legacyx-dashboard-card"><span class="legacyx-card-number">06</span><h3>Applications</h3><p>Track onboarding, funding, grants and other authorized applications.</p><span class="legacyx-coming-soon">Applications module</span></article><article class="legacyx-dashboard-card"><span class="legacyx-card-number">07</span><h3>Billing & Payments</h3><p>Engagement billing, invoices and payment history will connect to your client record.</p><span class="legacyx-coming-soon">Billing module</span></article><article class="legacyx-dashboard-card"><span class="legacyx-card-number">08</span><h3>Support</h3><p>Connect with the Legacy X Firm team regarding your relationship or portal access.</p><a class="legacyx-card-link" href="mailto:info@legacyxfirm.us">Contact Support</a></article></div></div><?php endif; ?></div></section></main><?php get_footer(); ?>
