<?php
if (!defined('ABSPATH')) exit;
if (!is_user_logged_in()) { wp_safe_redirect(wp_login_url(home_url('/credit-capital-center/'))); exit; }
get_header();
$user=wp_get_current_user();$client=legacyx_find_client_by_wp_user(get_current_user_id());$data=$client?legacyx_creditos_get_client_data($client->ID):legacyx_creditos_defaults();$personal=$data['personal_steps'];$business=$data['business_steps'];
function legacyx_creditos_stage_index($stage){$map=array('Not Started'=>0,'Intake'=>1,'Review'=>2,'Action Plan'=>3,'Building'=>4,'Funding Ready'=>6,'Monitoring'=>7);return $map[$stage]??0;}
$pdone=legacyx_creditos_stage_index($data['personal_stage']);$bdone=legacyx_creditos_stage_index($data['business_stage']);
?>
<main class="legacyx-credit-center"><div class="legacyx-credit-shell"><a class="legacyx-credit-back" href="<?php echo esc_url(home_url('/client-portal/')); ?>">← Client Command Center</a><header class="legacyx-credit-head"><div><span class="kicker">LEGACY X FIRM CREDITOS</span><h1>Credit & Capital Center</h1><p>One coordinated operating view for personal credit, business credit and capital readiness.</p></div><div class="legacyx-credit-identity"><span>Client</span><strong><?php echo esc_html($user->display_name?:$user->user_login); ?></strong><?php if($client): ?><small><?php echo esc_html(get_post_meta($client->ID,'_legacyx_client_id',true)); ?></small><?php endif; ?></div></header>
<?php if(!$client): ?><div class="legacyx-portal-notice"><strong>CreditOS connection pending.</strong> Your Universal Client Profile must be connected before private credit progress can be displayed.</div><?php else: ?>
<section class="legacyx-credit-summary"><div><span>Personal Track</span><strong><?php echo esc_html($data['personal_stage']); ?></strong></div><div><span>Business Track</span><strong><?php echo esc_html($data['business_stage']); ?></strong></div><div><span>Personal Score / Range</span><strong><?php echo esc_html($data['personal_score']?:'Not recorded'); ?></strong></div><div><span>Funding Goal</span><strong><?php echo esc_html($data['funding_goal']?:get_post_meta($client->ID,'_legacyx_capital_goal',true)?:'Not set'); ?></strong></div></section>
<section class="legacyx-credit-action"><span>Next Recommended Action</span><p><?php echo esc_html($data['next_action']); ?></p></section>
<div class="legacyx-credit-tracks"><section class="legacyx-credit-track"><div class="legacyx-track-title"><span>PERSONAL CREDIT</span><h2>7-Step Personal Credit System</h2><p>Structured progression from profile review through funding readiness and long-term monitoring.</p></div><div class="legacyx-step-list"><?php foreach($personal as $i=>$step):$n=$i+1;$done=$n<=$pdone; ?><article class="legacyx-credit-step <?php echo $done?'is-complete':''; ?>"><span class="legacyx-step-num"><?php echo sprintf('%02d',$n); ?></span><div><h3><?php echo esc_html($step); ?></h3><p><?php echo $done?'Completed / active in your current workflow.':'Upcoming step in your CreditOS roadmap.'; ?></p></div><b><?php echo $done?'✓':'→'; ?></b></article><?php endforeach; ?></div></section>
<section class="legacyx-credit-track"><div class="legacyx-track-title"><span>BUSINESS CREDIT</span><h2>7-Step Business Credit System</h2><p>Build a fundable business profile from entity compliance through bureau development and capital growth.</p></div><div class="legacyx-step-list"><?php foreach($business as $i=>$step):$n=$i+1;$done=$n<=$bdone; ?><article class="legacyx-credit-step <?php echo $done?'is-complete':''; ?>"><span class="legacyx-step-num"><?php echo sprintf('%02d',$n); ?></span><div><h3><?php echo esc_html($step); ?></h3><p><?php echo $done?'Completed / active in your current workflow.':'Upcoming step in your CreditOS roadmap.'; ?></p></div><b><?php echo $done?'✓':'→'; ?></b></article><?php endforeach; ?></div></section></div>
<section class="legacyx-credit-disclaimer"><strong>CreditOS is an organizational and educational workflow.</strong><p>Credit outcomes, approvals, limits, rates and funding decisions are determined by creditors, lenders and reporting agencies and are not guaranteed by Legacy X Firm.</p></section>
<?php endif; ?></div></main><?php get_footer(); ?>
