<?php
if(!defined('ABSPATH'))exit;
if(!is_user_logged_in()){wp_safe_redirect(wp_login_url(home_url('/documents-tasks/')));exit;}
get_header();
$user=wp_get_current_user();$client=legacyx_find_client_by_wp_user(get_current_user_id());$items=$client?legacyx_get_client_workflow($client->ID):array();$counts=$client?legacyx_workflow_counts($client->ID):array('open'=>0,'documents'=>0,'completed'=>0);
?>
<main class="legacyx-workflow-center"><div class="legacyx-credit-shell"><a class="legacyx-credit-back" href="<?php echo esc_url(home_url('/client-portal/')); ?>">← Client Command Center</a><header class="legacyx-credit-head"><div><span class="kicker">LEGACY X FIRM OS · WORKFLOW</span><h1>Documents & Tasks</h1><p>Your private action center for document requests, advisor tasks, deadlines and workflow progress.</p></div><div class="legacyx-credit-identity"><span>Client</span><strong><?php echo esc_html($user->display_name?:$user->user_login); ?></strong><?php if($client): ?><small><?php echo esc_html(get_post_meta($client->ID,'_legacyx_client_id',true)); ?></small><?php endif; ?></div></header>
<?php if(!$client): ?><div class="legacyx-portal-notice"><strong>Workflow connection pending.</strong> Your Universal Client Profile must be connected before private documents and tasks can be displayed.</div><?php else: ?>
<section class="legacyx-workflow-summary"><div><span>Open Items</span><strong><?php echo esc_html($counts['open']); ?></strong></div><div><span>Document Items</span><strong><?php echo esc_html($counts['documents']); ?></strong></div><div><span>Completed</span><strong><?php echo esc_html($counts['completed']); ?></strong></div></section>
<div class="legacyx-workflow-list">
<?php if(!$items): ?><div class="legacyx-workflow-empty"><span>WORKFLOW CLEAR</span><h2>No active items yet.</h2><p>Your Legacy X Firm advisor can assign tasks, request documents and publish approved client documents to this workspace.</p></div><?php else: foreach($items as $item):$type=get_post_meta($item->ID,'_legacyx_work_type',true);$status=get_post_meta($item->ID,'_legacyx_work_status',true);$due=get_post_meta($item->ID,'_legacyx_due_date',true);$priority=get_post_meta($item->ID,'_legacyx_priority',true);$note=get_post_meta($item->ID,'_legacyx_advisor_note',true);$url=get_post_meta($item->ID,'_legacyx_document_url',true);?>
<article class="legacyx-workflow-item"><div class="legacyx-workflow-main"><div class="legacyx-workflow-meta"><span><?php echo esc_html($type?:'Task'); ?></span><span><?php echo esc_html($priority?:'Normal'); ?> priority</span><?php if($due): ?><span>Due <?php echo esc_html(date_i18n(get_option('date_format'),strtotime($due))); ?></span><?php endif; ?></div><h2><?php echo esc_html(get_the_title($item)); ?></h2><?php if($item->post_content): ?><p><?php echo esc_html(wp_strip_all_tags($item->post_content)); ?></p><?php endif; ?><?php if($note): ?><div class="legacyx-workflow-note"><strong>Advisor Next Action</strong><p><?php echo nl2br(esc_html($note)); ?></p></div><?php endif; ?><?php if($url): ?><a class="legacyx-card-link" href="<?php echo esc_url($url); ?>" target="_blank" rel="noopener noreferrer">Open Document →</a><?php endif; ?></div><div class="legacyx-workflow-status"><span>Status</span><strong><?php echo esc_html($status?:'Open'); ?></strong></div></article>
<?php endforeach; endif; ?>
</div><section class="legacyx-credit-disclaimer"><strong>Private workflow notice.</strong><p>Only use document links approved for client access. Sensitive files should be stored in an appropriately protected document system rather than the public website repository.</p></section>
<?php endif; ?></div></main><?php get_footer(); ?>